import {
  Camera,
  Wand,
  MessageSquare,
  Bell,
  Inbox,
  Landmark,
  UtensilsCrossed,
  ChefHat,
  Wine,
  FileSpreadsheet,
  HandCoins,
  HardHat,
  Calculator,
  FolderKanban,
  Hotel,
  TrendingUp,
  BedDouble,
  Monitor,
  Clock,
  ReceiptText,
  ShoppingCart,
  Store,
  BarChart3,
  Layers,
  Puzzle,
  TextSearch,
  Ship,
  FileText,
  Shield,
  Building2,
  ArrowRightLeft,
  Mail,
  MessageCircle,
  type LucideIcon,
} from 'lucide-react'

// Exported so callers can resolve icons with a plain lookup. The react-hooks
// static-components rule treats a call-result component (`resolveIcon(...)`)
// as "created during render", while a static map lookup is accepted.
export const EXTENSION_ICON_MAP: Record<string, LucideIcon> = {
  Camera,
  Wand,
  MessageSquare,
  Bell,
  Inbox,
  Landmark,
  UtensilsCrossed,
  ChefHat,
  Wine,
  FileSpreadsheet,
  HandCoins,
  HardHat,
  Calculator,
  FolderKanban,
  Hotel,
  TrendingUp,
  BedDouble,
  Monitor,
  Clock,
  ReceiptText,
  ShoppingCart,
  Store,
  BarChart3,
  Layers,
  Puzzle,
  TextSearch,
  Ship,
  FileText,
  Shield,
  Building2,
  ArrowRightLeft,
  Mail,
  MessageCircle,
}

export const FALLBACK_EXTENSION_ICON: LucideIcon = Puzzle

export function resolveIcon(name: string): LucideIcon {
  return EXTENSION_ICON_MAP[name] ?? FALLBACK_EXTENSION_ICON
}
