/**
 * Skatteverket SRU field codes (fältkoder) per blankett, beskattningsperiod 2025P4.
 *
 * Generated from Skatteverket's field-name tables in
 * _Nyheter_from_beskattningsperiod_2025P4.zip (INK2_SKV2002-33-01-24-04,
 * INK2R_SKV2002-33-01-24-04, INK2S_SKV2002-33-01-24-04, NE_SKV2161-13-02-25-02),
 * published at skatteverket.se → Teknisk information om filöverföring.
 *
 * This is the source of truth for which codes a BLANKETTER.SRU block may contain.
 * The engines map BAS accounts onto these codes; tests assert they never emit
 * a code outside this list. Update the list — and re-check the engines — when
 * Skatteverket publishes a new beskattningsperiod.
 */

export interface SkvFieldCode {
  code: string
  label: string
  /** Skatteverket datatype, e.g. Numeriskt_A (may be negative), Numeriskt_B (non-negative), Str_X. */
  datatype: string
}

export const SKV_INK2_FIELDS: readonly SkvFieldCode[] = [
  { code: '7104', label: '1.1 Överskott av näringsverksamhet', datatype: 'Numeriskt_B' },
  { code: '7114', label: '1.2 Underskott av näringsverksamhet', datatype: 'Numeriskt_B' },
  { code: '7131', label: '1.3 Kreditinstituts underlag för riskskatt', datatype: 'Numeriskt_13' },
  { code: '7132', label: '1.4 Underlag för särskild löneskatt på pensionskostnader', datatype: 'Numeriskt_B' },
  { code: '7133', label: '1.5 Negativt underlag för särskild löneskatt på pensionskostnader', datatype: 'Numeriskt_B' },
  { code: '7153', label: '1.6 a Försäkringsföretag m.fl. samt avsatt till pensioner 15 %', datatype: 'Numeriskt_B' },
  { code: '7154', label: '1.6 b Utländska pensions- försäkringar 15 %', datatype: 'Numeriskt_B' },
  { code: '7155', label: '1.7 a Försäkringsföretag m.fl 30 %', datatype: 'Numeriskt_B' },
  { code: '7156', label: '1.7 b Utländska kapitalförsäkringar 30 %', datatype: 'Numeriskt_B' },
  { code: '80', label: '1.8 Småhus/ ägarlägenhet', datatype: 'Numeriskt_B' },
  { code: '93', label: '1.9 Hyreshus: bostäder', datatype: 'Numeriskt_B' },
  { code: '84', label: '1.10 Småhus/ägarlägenhet: tomtmark, byggnad under uppförande', datatype: 'Numeriskt_B' },
  { code: '86', label: '1.11 Hyreshus: tomtmark, bostäder under uppförande', datatype: 'Numeriskt_B' },
  { code: '95', label: '1.12 Hyreshus: lokaler', datatype: 'Numeriskt_B' },
  { code: '96', label: '1.13 Industrienhet och elproduktionsenhet: värme- kraftverk', datatype: 'Numeriskt_B' },
  { code: '97', label: '1.14 Elproduktionsenhet, vattenkraftverk', datatype: 'Numeriskt_B' },
  { code: '98', label: '1.15 Elproduktionsenhet, vindkraftverk', datatype: 'Numeriskt_B' },
  { code: '90', label: 'Övriga upplysningar på bilaga', datatype: 'Str_X' },
  { code: '1582', label: '1.16 Förnybar el (kilowattimmar)', datatype: 'Numeriskt_10' },
]

export const SKV_INK2R_FIELDS: readonly SkvFieldCode[] = [
  { code: '7201', label: '2.1 Immateriella anläggningstillgångar Koncessioner, patent, licenser, varumärken, hyresrätter, goodwill och liknande rättigheter', datatype: 'Numeriskt_A' },
  { code: '7202', label: '2.2 Immateriella anläggningstillgångar Förskott avseende immateriella anläggningstillgångar', datatype: 'Numeriskt_A' },
  { code: '7214', label: '2.3 Materiella anläggningstillgångar Byggnader och mark', datatype: 'Numeriskt_A' },
  { code: '7215', label: '2.4 Materiella anläggningstillgångar Maskiner, inventarier och övriga materiella anläggningstillgångar', datatype: 'Numeriskt_A' },
  { code: '7216', label: '2.5 Materiella anläggningstillgångar Förbättringsutgifter på annans fastighet', datatype: 'Numeriskt_A' },
  { code: '7217', label: '2.6 Materiella anläggningstillgångar Pågående nyanläggningar och förskott avseende materiella anläggningstillgångar', datatype: 'Numeriskt_A' },
  { code: '7230', label: '2.7 Finansiella anläggningstillgångar Andelar i koncernföretag', datatype: 'Numeriskt_A' },
  { code: '7231', label: '2.8 Finansiella anläggningstillgångar Andelar i intresseföretag och gemensamt styrda företag', datatype: 'Numeriskt_A' },
  { code: '7233', label: '2.9 Ägarintressen i övriga företag och andra långfristiga värdepappersinnehav', datatype: 'Numeriskt_A' },
  { code: '7232', label: '2.10 Finansiella anläggningstillgångar Fordringar hos koncern-, intresse- och gemensamt styrda företag', datatype: 'Numeriskt_A' },
  { code: '7234', label: '2.11 Finansiella anläggningstillgångar Lån till delägare eller närstående', datatype: 'Numeriskt_A' },
  { code: '7235', label: '2.12 Fordringar hos övriga företag som det finns ett ägarintresse i och andra långfristiga fordringar', datatype: 'Numeriskt_A' },
  { code: '7241', label: '2.13 Varulager m.m. Råvaror och förnödenheter', datatype: 'Numeriskt_A' },
  { code: '7242', label: '2.14 Varulager Varor under tillverkning', datatype: 'Numeriskt_A' },
  { code: '7243', label: '2.15 Varulager Färdiga varor och handelsvaror', datatype: 'Numeriskt_A' },
  { code: '7244', label: '2.16 Varulager Övriga lagertillgångar', datatype: 'Numeriskt_A' },
  { code: '7245', label: '2.17 Varulager Pågående arbeten för annans räkning', datatype: 'Numeriskt_A' },
  { code: '7246', label: '2.18 Varulager Förskott till leverantörer', datatype: 'Numeriskt_A' },
  { code: '7251', label: '2.19 Kortfristiga fordringar Kundfordringar', datatype: 'Numeriskt_A' },
  { code: '7252', label: '2.20 Kortfristiga fordringar Fordringar hos koncern-, intresse- och gemensamt styrda företag', datatype: 'Numeriskt_A' },
  { code: '7261', label: '2.21 Fordringar hos övriga företag som det finns ett ägarintresse i och övriga fordringar', datatype: 'Numeriskt_A' },
  { code: '7262', label: '2.22 Kortfristiga fordringar Upparbetad men ej fakturerad intäkt', datatype: 'Numeriskt_A' },
  { code: '7263', label: '2.23 Kortfristiga fordringar Förutbetalda kostnader och upplupna intäkter', datatype: 'Numeriskt_A' },
  { code: '7270', label: '2.24 Kortfristiga placeringar Andelar i koncernföretag', datatype: 'Numeriskt_A' },
  { code: '7271', label: '2.25 Kortfristiga placeringar Övriga kortfristiga placeringar', datatype: 'Numeriskt_A' },
  { code: '7281', label: '2.26 Kassa och bank Kassa, bank och redovisningsmedel', datatype: 'Numeriskt_A' },
  { code: '7301', label: '2.27 Eget kapital Bundet eget kapital', datatype: 'Numeriskt_A' },
  { code: '7302', label: '2.28 Eget kapital Fritt eget kapital', datatype: 'Numeriskt_A' },
  { code: '7321', label: '2.29 Obeskattade reserver Periodiseringsfonder', datatype: 'Numeriskt_A' },
  { code: '7322', label: '2.30 Obeskattade reserver Ackumulerade överavskrivningar', datatype: 'Numeriskt_A' },
  { code: '7323', label: '2.31 Obeskattade reserver Övriga obeskattade reserver', datatype: 'Numeriskt_A' },
  { code: '7331', label: '2.32 Avsättningar Avsättningar för pensioner och liknande förpliktelser enligt lag (1967:531)...', datatype: 'Numeriskt_A' },
  { code: '7332', label: '2.33 Avsättningar Övriga avsättningar för pensioner och liknande förpliktelser', datatype: 'Numeriskt_A' },
  { code: '7333', label: '2.34 Avsättningar Övriga avsättningar', datatype: 'Numeriskt_A' },
  { code: '7350', label: '2.35 Långfristiga skulder Obligationslån', datatype: 'Numeriskt_A' },
  { code: '7351', label: '2.36 Långfristiga skulder Checkräkningskredit', datatype: 'Numeriskt_A' },
  { code: '7352', label: '2.37 Långfristiga skulder Övriga skulder till kreditinstitut', datatype: 'Numeriskt_A' },
  { code: '7353', label: '2.38 Långfristiga skulder Skulder till koncern-, intresse- och gemensamt styrda företag', datatype: 'Numeriskt_A' },
  { code: '7354', label: '2.39 Skulder till övriga företag som det finns ett ägarintresse i och övriga skulder', datatype: 'Numeriskt_A' },
  { code: '7360', label: '2.40 Kortfristiga skulder Checkräkningskredit', datatype: 'Numeriskt_A' },
  { code: '7361', label: '2.41 Kortfristiga skulder Övriga skulder till kreditinstitut', datatype: 'Numeriskt_A' },
  { code: '7362', label: '2.42 Kortfristiga skulder Förskott från kunder', datatype: 'Numeriskt_A' },
  { code: '7363', label: '2.43 Kortfristiga skulder Pågående arbeten för annans räkning', datatype: 'Numeriskt_A' },
  { code: '7364', label: '2.44 Kortfristiga skulder Fakturerad men ej upparbetad intäkt', datatype: 'Numeriskt_A' },
  { code: '7365', label: '2.45 Kortfristiga skulder Leverantörsskulder', datatype: 'Numeriskt_A' },
  { code: '7366', label: '2.46 Kortfristiga skulder Växelskulder', datatype: 'Numeriskt_A' },
  { code: '7367', label: '2.47 Kortfristiga skulder Skulder till koncern-, intresse- och gemensamt styrda företag', datatype: 'Numeriskt_A' },
  { code: '7369', label: '2.48 Skulder till övriga företag som det finns ett ägarintresse i och övriga skulder', datatype: 'Numeriskt_A' },
  { code: '7368', label: '2.49 Kortfristiga skulder Skattesskulder', datatype: 'Numeriskt_A' },
  { code: '7370', label: '2.50 Kortfristiga skulder Upplupna kostnader och förutbetalda intäkter', datatype: 'Numeriskt_A' },
  { code: '7410', label: '3.1 Nettoomsättning', datatype: 'Numeriskt_A' },
  { code: '7411', label: '3.2 Förändring av lager av produkter i arbete, färdiga varor och pågående arbete för annans räkning. +', datatype: 'Numeriskt_A' },
  { code: '7510', label: '3.2 Förändring av lager av produkter i arbete, färdiga varor och pågående arbete för annans räkning. -', datatype: 'Numeriskt_A' },
  { code: '7412', label: '3.3 Aktiverat arbete för egen räkning', datatype: 'Numeriskt_A' },
  { code: '7413', label: '3.4 Övriga rörelseintäkter', datatype: 'Numeriskt_A' },
  { code: '7511', label: '3.5 Råvaror och förnödenheter', datatype: 'Numeriskt_A' },
  { code: '7512', label: '3.6 Handelsvaror', datatype: 'Numeriskt_A' },
  { code: '7513', label: '3.7 Övriga externa kostnader', datatype: 'Numeriskt_A' },
  { code: '7514', label: '3.8 Personalkostnader', datatype: 'Numeriskt_A' },
  { code: '7515', label: '3.9 Av- och nedskrivningar av materiella och immateriella anläggningstillgångar', datatype: 'Numeriskt_A' },
  { code: '7516', label: '3.10 Nedskrivningar av omsättningstillgångar utöver normala nedskrivningar', datatype: 'Numeriskt_A' },
  { code: '7517', label: '3.11 Övriga rörelsekostnader', datatype: 'Numeriskt_A' },
  { code: '7414', label: '3.12 Resultat från andelar i koncernföretag +', datatype: 'Numeriskt_A' },
  { code: '7518', label: '3.12 Resultat från andelar i koncernföretag -', datatype: 'Numeriskt_A' },
  { code: '7415', label: '3.13 Resultat från andelar i intresseföretag och gemensamt styrda företag +', datatype: 'Numeriskt_A' },
  { code: '7519', label: '3.13 Resultat från andelar i intresseföretag och gemensamt styrda företag -', datatype: 'Numeriskt_A' },
  { code: '7423', label: '3.14 Resultat från övriga företag som det finns ett ägarintresse i +', datatype: 'Numeriskt_A' },
  { code: '7530', label: '3.14 Resultat från övriga företag som det finns ett ägarintresse i -', datatype: 'Numeriskt_A' },
  { code: '7416', label: '3.15 Resultat från övriga finansiella anläggningstillgångar +', datatype: 'Numeriskt_A' },
  { code: '7520', label: '3.15 Resultat från övriga finansiella anläggningstillgångar -', datatype: 'Numeriskt_A' },
  { code: '7417', label: '3.16 Övriga ränteintäkter och liknande resultatposter', datatype: 'Numeriskt_A' },
  { code: '7521', label: '3.17 Nedskrivning av finansiella anläggningstillgångar och kortfristiga placeringar', datatype: 'Numeriskt_A' },
  { code: '7522', label: '3.18 Räntekostnader och liknande resultatposter', datatype: 'Numeriskt_A' },
  { code: '7524', label: '3.19 Lämnade koncernbidrag', datatype: 'Numeriskt_A' },
  { code: '7419', label: '3.20 Mottagna koncernbidrag', datatype: 'Numeriskt_A' },
  { code: '7420', label: '3.21 Återföring av periodiseringsfond', datatype: 'Numeriskt_B' },
  { code: '7525', label: '3.22 Avsättning till periodiseringsfond', datatype: 'Numeriskt_B' },
  { code: '7421', label: '3.23 Förändring av överavskrivningar +', datatype: 'Numeriskt_A' },
  { code: '7526', label: '3.23 Förändring av överavskrivningar -', datatype: 'Numeriskt_A' },
  { code: '7422', label: '3.24 Övriga bokslutsdispositioner +', datatype: 'Numeriskt_A' },
  { code: '7527', label: '3.24 Övriga bokslutsdispositioner -', datatype: 'Numeriskt_A' },
  { code: '7528', label: '3.25 Skatt på årets resultat', datatype: 'Numeriskt_A' },
  { code: '7450', label: '3.26 Årets resultat, vinst (flyttas till p. 4.1)', datatype: 'Numeriskt_B' },
  { code: '7550', label: '3.27 Årets resultat, förlust (flyttas till p. 4.2)', datatype: 'Numeriskt_B' },
]

export const SKV_INK2S_FIELDS: readonly SkvFieldCode[] = [
  { code: '7650', label: '4.1 Årets resultat, vinst', datatype: 'Numeriskt_B' },
  { code: '7750', label: '4.2 Årets resultat, förlust', datatype: 'Numeriskt_B' },
  { code: '7651', label: '4.3a. Bokförda kostnader som inte ska dras av: a. Skatt på årets resultat', datatype: 'Numeriskt_A' },
  { code: '7652', label: 'b. Bokförda kostnader som inte ska dras av: b. Nedskrivning av finansiella tillgångar', datatype: 'Numeriskt_A' },
  { code: '7653', label: 'c. Bokförda kostnader som inte ska dras av: c. Andra bokförda kostnader', datatype: 'Numeriskt_A' },
  { code: '7751', label: '4.4a. Kostnader som ska dras av men som inte ingår i det redovisade resultatet: a. Lämnade koncernbidrag', datatype: 'Numeriskt_A' },
  { code: '7764', label: 'b. Kostnader som ska dras av men som inte ingår i det redovisade resultatet: b. Andra ej bokförda kostnader', datatype: 'Numeriskt_A' },
  { code: '7752', label: '4.5a. Bokförda intäkter som inte ska tas upp: a. Ackordsvinster', datatype: 'Numeriskt_A' },
  { code: '7753', label: 'b. Bokförda intäkter som inte ska tas upp: b. Utdelning', datatype: 'Numeriskt_A' },
  { code: '7754', label: 'c. Bokförda intäkter som inte ska tas upp: c. Andra bokförda intäkter', datatype: 'Numeriskt_A' },
  { code: '7654', label: '4.6a. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet a. Beräknad schablonintäkt på periodiseringsfonder vid beskattningsårets ingång', datatype: 'Numeriskt_B' },
  { code: '7668', label: 'b. Beräknad schablonintäkt på fondandelar ägda vid kalenderårets ingång', datatype: 'Numeriskt_A' },
  { code: '7655', label: 'c. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: c. Mottagna koncernbidrag', datatype: 'Numeriskt_A' },
  { code: '7673', label: 'd. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: d. Uppräknat belopp vid återföring av periodiseringsfond', datatype: 'Numeriskt_A' },
  { code: '7665', label: 'e. Intäkter som ska tas upp men som inte ingår i det redovisade resultatet: e. Andra ej bokförda intäkter', datatype: 'Numeriskt_A' },
  { code: '7755', label: '4.7a. Avyttring av delägarrätter: a. Bokförd vinst', datatype: 'Numeriskt_B' },
  { code: '7656', label: 'b. Avyttring av delägarrätter: b. Bokförd förlust', datatype: 'Numeriskt_B' },
  { code: '7756', label: 'c. Avyttring av delägarrätter: c. Uppskov med kapitalvinst enligt blankett N4', datatype: 'Numeriskt_B' },
  { code: '7657', label: 'd. Avyttring av delägarrätter: d. Återfört uppskov med kapitalvinst enligt blankett N4', datatype: 'Numeriskt_B' },
  { code: '7658', label: 'e. Avyttring av delägarrätter: e. Kapitalvinst för beskattningsåret', datatype: 'Numeriskt_B' },
  { code: '7757', label: 'f. Avyttring av delägarrätter: f. Kapitalförlust som ska dras av', datatype: 'Numeriskt_B' },
  { code: '7758', label: '4.8a. Andel i handelsbolag (inkl. avyttring): a. Bokförd intäkt/vinst', datatype: 'Numeriskt_B' },
  { code: '7659', label: 'b. Andel i handelsbolag (inkl. avyttring): b. Skattemässigt överskott enligt N3B', datatype: 'Numeriskt_B' },
  { code: '7660', label: 'c. Andel i handelsbolag (inkl. avyttring): c. Bokförd kostnad/förlust', datatype: 'Numeriskt_B' },
  { code: '7759', label: 'd. Andel i handelsbolag (inkl. avyttring): d. Skattemässigt underskott enligt N3B', datatype: 'Numeriskt_B' },
  { code: '7666', label: '4.9 Skattemässig justering av bokfört resultat för avskrivningar på byggnader och annan fast egendom samt restvärdesavskrivning på maskiner och inventarier (+)', datatype: 'Numeriskt_B' },
  { code: '7765', label: '4.9 Skattemässig justering av bokfört resultat för avskrivningar på byggnader och annan fast egendom samt restvärdesavskrivning på maskiner och inventarier (-)', datatype: 'Numeriskt_B' },
  { code: '7661', label: '4.10 Skattemässig justering av bokfört resultat vid avyttring av näringsfastighet och näringsbostadsrätt', datatype: 'Numeriskt_B' },
  { code: '7760', label: '4.10 Skattemässig korrigering av bokfört resultat vid avyttring av näringsfastighet och näringsbostadsrätt: -', datatype: 'Numeriskt_B' },
  { code: '7761', label: '4.11 Skogs-/substansminskningsavdrag (specificeras på blankett N8)', datatype: 'Numeriskt_B' },
  { code: '7662', label: '4.12 Återföringar vid avyttring av fastighet t.ex. värdeminskningsavdrag, skogsavdrag och substansminskningsavdrag...', datatype: 'Numeriskt_A' },
  { code: '7663', label: '4.13 Andra skattemässiga justeringar av resultatet: +', datatype: 'Numeriskt_B' },
  { code: '7762', label: '4.13 Andra skattemässiga justeringar av resultatet: -', datatype: 'Numeriskt_B' },
  { code: '7763', label: '4.14a. Underskott: a. Outnyttjat underskott från föregående år', datatype: 'Numeriskt_B' },
  { code: '7671', label: '4.14b. Reduktion av outnyttjat underskott med hänsyn till beloppsspärr, ackord eller konkurs', datatype: 'Numeriskt_A' },
  { code: '7672', label: '4.14c. Reduktion av outnyttjat underskott med hänsyn till koncernbidragsspärr, fusionsspärr m.m. (beloppet ska också tas upp vid p. 1.2. på sid. 1)', datatype: 'Numeriskt_A' },
  { code: '7670', label: '4.15 Överskott (flyttas till p. 1.1 på sid. 1)', datatype: 'Numeriskt_B' },
  { code: '7770', label: '4.16 Underskott (flyttas till p. 1.2 på sid. 1)', datatype: 'Numeriskt_B' },
  { code: '8020', label: '4.17 Årets begärda och tidigare års medgivna värdeminskningsavdrag som finns vid beskattningsårets utgång avseende byggnader.', datatype: 'Numeriskt_A' },
  { code: '8021', label: '4.18 Årets begärda och tidigare års medgivna värdeminskningsavdrag som finns vid beskattningsårets utgång avseende markanläggningar.', datatype: 'Numeriskt_A' },
  { code: '8023', label: '4.19 Vid restvärdesavskrivning: återförda belopp för av- och nedskrivning, försäljning, utrangering', datatype: 'Numeriskt_B' },
  { code: '8026', label: '4.20 Lån från aktieägare (fysisk person) vid räkenskapsårets utgång', datatype: 'Numeriskt_B' },
  { code: '8022', label: '4.21 Pensionskostnader (som ingår i p. 3.8)', datatype: 'Numeriskt_A' },
  { code: '8028', label: '4.22 Koncernbidragsspärrat och fusionsspärrat underskott m.m. (frivillig uppgift)', datatype: 'Numeriskt_B' },
  { code: '8040', label: 'Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsredovisningen: Ja', datatype: 'Str_X' },
  { code: '8041', label: 'Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsredovisningen: Nej', datatype: 'Str_X' },
  { code: '8044', label: 'Årsredovisningen har varit föremål för revision: Ja', datatype: 'Str_X' },
  { code: '8045', label: 'Årsredovisningen har varit föremål för revision: Nej', datatype: 'Str_X' },
]

export const SKV_NE_FIELDS: readonly SkvFieldCode[] = [
  { code: '7020', label: 'Verksamhetens art', datatype: 'Str_80' },
  { code: '7021', label: 'Jag har bedrivit passiv näringsverksamhet', datatype: 'Str_X' },
  { code: '7024', label: 'Självständig näringsverksamhet bedrivs utanför EES', datatype: 'Str_X' },
  { code: '7023', label: 'Jag har inte tillämpat reglerna om förenklat årsbokslut', datatype: 'Str_X' },
  { code: '7025', label: 'Personnummer redovisningsansvarig', datatype: 'Orgnr_Id_PD' },
  { code: '7200', label: 'B1. Immateriella anläggningstillgångar', datatype: 'Numeriskt_A' },
  { code: '7210', label: 'B2. Byggnader och markanläggningar', datatype: 'Numeriskt_A' },
  { code: '7211', label: 'B3. Mark och andra tillgångar som inte får skrivas av', datatype: 'Numeriskt_A' },
  { code: '7212', label: 'B4. Maskiner och inventarier', datatype: 'Numeriskt_A' },
  { code: '7213', label: 'B5. Övriga anläggningstillgångar', datatype: 'Numeriskt_A' },
  { code: '7240', label: 'B6. Varulager', datatype: 'Numeriskt_A' },
  { code: '7250', label: 'B7. Kundfordringar', datatype: 'Numeriskt_A' },
  { code: '7260', label: 'B8. Övriga fordringar', datatype: 'Numeriskt_A' },
  { code: '7280', label: 'B9. Kassa och bank', datatype: 'Numeriskt_A' },
  { code: '7300', label: 'B10. Eget kapital (tillgångar - skulder)', datatype: 'Numeriskt_A' },
  { code: '7320', label: 'B11. Obeskattade reserver', datatype: 'Numeriskt_A' },
  { code: '7330', label: 'B12. Avsättningar', datatype: 'Numeriskt_A' },
  { code: '7380', label: 'B13. Låneskulder', datatype: 'Numeriskt_A' },
  { code: '7381', label: 'B14. Skatteskulder', datatype: 'Numeriskt_A' },
  { code: '7382', label: 'B15. Leverantörsskulder', datatype: 'Numeriskt_A' },
  { code: '7383', label: 'B16. Övriga skulder', datatype: 'Numeriskt_A' },
  { code: '7400', label: 'R1. Försäljning och utfört arbete samt övriga momspliktiga intäkter', datatype: 'Numeriskt_A' },
  { code: '7401', label: 'R2. Momsfria intäkter', datatype: 'Numeriskt_A' },
  { code: '7402', label: 'R3. Bil- och bostadsförmån m.m.', datatype: 'Numeriskt_A' },
  { code: '7403', label: 'R4. Ränteintäkter m.m.', datatype: 'Numeriskt_A' },
  { code: '7500', label: 'R5. Varor, material och tjänster', datatype: 'Numeriskt_A' },
  { code: '7501', label: 'R6. Övriga externa kostnader', datatype: 'Numeriskt_A' },
  { code: '7502', label: 'R7. Anställd personal', datatype: 'Numeriskt_A' },
  { code: '7503', label: 'R8. Räntekostnader m.m.', datatype: 'Numeriskt_A' },
  { code: '7504', label: 'R9. Avskrivningar och nedskrivningar byggnader och markanläggningar', datatype: 'Numeriskt_A' },
  { code: '7505', label: 'R10. Avskrivningar och nedskrivningar maskiner, inventarier och immateriella tillgångar', datatype: 'Numeriskt_A' },
  { code: '7440', label: 'R11. Bokfört resultat (förs över till sidan 2. R12)', datatype: 'Numeriskt_A' },
  { code: '8046', label: 'Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet: Ja', datatype: 'Str_X' },
  { code: '8047', label: 'Uppdragstagare (t.ex. redovisningskonsult) har biträtt vid upprättandet av årsbokslutet: Nej', datatype: 'Str_X' },
  { code: '7600', label: 'R12. Bokfört resultat (förs över från R11 sidan 1)', datatype: 'Numeriskt_A' },
  { code: '7601', label: 'R13. Bokförda kostnader som inte ska dras av', datatype: 'Numeriskt_B' },
  { code: '7700', label: 'R14. Bokförda intäkter som inte ska tas upp', datatype: 'Numeriskt_B' },
  { code: '7602', label: 'R15. Intäkter som inte bokförts men som ska tas upp', datatype: 'Numeriskt_B' },
  { code: '7701', label: 'R16. Kostnader som inte bokförts men som ska dras av', datatype: 'Numeriskt_B' },
  { code: '7702', label: 'R18. Gemensam verksamhet - överskott redovisad av annan eller min andel av underskott', datatype: 'Numeriskt_B' },
  { code: '7603', label: 'R19. Gemensam verksamhet - underskott redovisad av annan eller min andel av överskott', datatype: 'Numeriskt_B' },
  { code: '7614', label: 'R20. Min andel som medhjälpande make (+)', datatype: 'Numeriskt_B' },
  { code: '7703', label: 'R20. andel till medhjälpande make (-)', datatype: 'Numeriskt_B' },
  { code: '7704', label: 'R22. Övriga skattemässiga justeringar, kostnader min andel', datatype: 'Numeriskt_B' },
  { code: '7604', label: 'R23. Övriga skattemässiga justeringar, intäkter min andel', datatype: 'Numeriskt_B' },
  { code: '7705', label: 'R24. Outnyttjat underskott från föregående beskattningsår (R48 i föregående års blankett)', datatype: 'Numeriskt_B' },
  { code: '7706', label: 'R25. Skogsavdrag/substansminskningsavdrag enligt blankett N8', datatype: 'Numeriskt_B' },
  { code: '7605', label: 'R26. Återföring av värdeminskningsavdrag m.m. vid avyttring av näringsfastighet och s.k. avskattning (skogs- och substansminskningsavdrag redovisas även på N8)', datatype: 'Numeriskt_B' },
  { code: '7606', label: 'R27. Uttag från skogs-, skogsskade- eller upphovsmannakonto', datatype: 'Numeriskt_B' },
  { code: '7707', label: 'R28. Inbetalning till skogs-, skogsskade- eller upphovsmannakonto', datatype: 'Numeriskt_B' },
  { code: '7708', label: 'R30. Positiv räntefördelning, dock högst överskott vid R29 (beloppet förs även till p. 11.1 på INK1)', datatype: 'Numeriskt_B' },
  { code: '7607', label: 'R31. Negativ räntefördelning (beloppet förs även till p. 11.2 på INK1)', datatype: 'Numeriskt_B' },
  { code: '7608', label: 'R32. Återföring av periodiseringsfond', datatype: 'Numeriskt_B' },
  { code: '7709', label: 'R34. Avsättning till periodiseringsfond, dock högst 30 % av överskott vid R33', datatype: 'Numeriskt_B' },
  { code: '7710', label: 'R36. Ökning av expansionsfond dock högst överskott vid R35 (beloppet förs även till p. 12.1 på INK1)', datatype: 'Numeriskt_B' },
  { code: '7609', label: 'R37. Minskning av expansionsfond (beloppet förs även till p. 12.2 på INK1)', datatype: 'Numeriskt_B' },
  { code: '7711', label: 'R38. Egna pensionspremier eller inbetalning på pensionssparkonto som dras av i näringsverksamheten', datatype: 'Numeriskt_B' },
  { code: '7712', label: 'R39. Särskild löneskatt på pensionssparavdrag i R38', datatype: 'Numeriskt_A' },
  { code: '7610', label: 'R40. Medgivna avdrag för egenavgifter och särskild löneskatt föregående beskattningsår (R43 i förgående års blankett)', datatype: 'Numeriskt_B' },
  { code: '7713', label: 'R41. Påförda egenavgifter och särskild löneskatt enligt slutskattebesked', datatype: 'Numeriskt_A' },
  { code: '7714', label: 'R43. Årets beräknade avdrag för egenavgifter och särskild löneskatt', datatype: 'Numeriskt_B' },
  { code: '7611', label: 'R44. Sjukpenning som hör till denna näringsverksamhet', datatype: 'Numeriskt_B' },
  { code: '7612', label: 'R45. Allmänt avdrag. Vid konstnärlig eller nystartad näringsverksamhet utnyttjat underskott (beloppet förs även till p. 14.1 på INK1)', datatype: 'Numeriskt_B' },
  { code: '7613', label: 'R46. Undersott som utnyttjas i kapital. Vinst vid avyttring av näringsfastighet/näringsbostadsrätt och underskott i andelshus', datatype: 'Numeriskt_B' },
  { code: '7630', label: 'R47. Överskott (+). Överförs till INK1 sidan 2, p.10.1 eller 10.3', datatype: 'Numeriskt_B' },
  { code: '7730', label: 'R48. Underskott (-). Överförs till INK1 sidan 2, p.10.2 eller 10.4. Nästa år förs beloppet till R24.', datatype: 'Numeriskt_B' },
  { code: '8000', label: '1. Har du dragit av kostnader för personbil eller lätt lastbil som är leasad....', datatype: 'Str_X' },
  { code: '8002', label: '2. Har du dragit av bilkostnader för egen bil enligt schablon (18,50 kr/mil), ange beloppet', datatype: 'Numeriskt_B' },
  { code: '8003', label: '3. Ränteutgifter enligt kontrolluppgifter för beskattningsåret som dragits av i näringsverksamhet, ange belopp', datatype: 'Numeriskt_B' },
  { code: '8004', label: '4. Vid restvärdesavskrivning: återförda belopp för av- och nedskrivning, försäljning och utrangering', datatype: 'Numeriskt_B' },
  { code: '8006', label: '5. Årets begärda och tidigare års medgivna värdeminskningsavdrag som finns vid beskattningsårets utgång avseende byggnader.', datatype: 'Numeriskt_B' },
  { code: '8007', label: '6. Årets begärda och tidigare års medgivna värdeminskningsavdrag som finns vid beskattningsårets utgång avseende markanläggningar.', datatype: 'Numeriskt_B' },
  { code: '8008', label: '7. Ersättningsfonder vid beskattningsårets utgång', datatype: 'Numeriskt_B' },
  { code: '8009', label: '8. Kapitalunderlag för räntefördelning (positivt)', datatype: 'Numeriskt_B' },
  { code: '8010', label: '9. Kapitalunderlag för räntefördelning (negativt)', datatype: 'Numeriskt_B' },
  { code: '8011', label: '10. Positivt fördelningsbelopp som sparas till nästa års taxering', datatype: 'Numeriskt_B' },
  { code: '8012', label: '11. Kapitalunderlag expansionsfond (positivt)', datatype: 'Numeriskt_B' },
]

function codeSet(fields: readonly SkvFieldCode[]): ReadonlySet<string> {
  return new Set(['7011', '7012', ...fields.map((f) => f.code)])
}

/** Codes allowed in each blankett block (7011/7012 fiscal-year dates included). */
export const SKV_FIELD_CODES = {
  INK2: codeSet(SKV_INK2_FIELDS),
  INK2R: codeSet(SKV_INK2R_FIELDS),
  INK2S: codeSet(SKV_INK2S_FIELDS),
  NE: codeSet(SKV_NE_FIELDS),
} as const
