/**
 * Shared customer-invoice payment orchestration ("mark paid").
 *
 * ONE implementation of the full settlement flow — used by the dashboard
 * route, the v1 API route and the pending-operation executor so partial
 * payments, overpayment→customer credit, underpayment ledger rows,
 * invoice_payments bookkeeping, race handling and event emission cannot
 * drift between entry points.
 *
 * Journal shapes:
 *   - Custom lines (partial payment dialogs)        → createJournalEntry
 *   - Overpayment                                   → payment + 2893/2440-style
 *                                                     customer-credit lines
 *   - Kontantmetoden (invoice never booked)         → createInvoiceCashEntry
 *   - Faktureringsmetoden (invoice booked at send)  → createInvoicePaymentJournalEntry
 *
 * The JE shape is driven by the INVOICE's booking state, not the company's
 * current accounting_method — an invoice booked at send must clear 1510 at
 * payment even if the company has since flipped to kontantmetoden.
 */
import { createHash } from 'node:crypto'
import type { SupabaseClient } from '@supabase/supabase-js'
import {
  createInvoiceCashEntry,
  createInvoicePaymentJournalEntry,
} from '@/lib/bookkeeping/invoice-entries'
import { createDraftEntry, findFiscalPeriod } from '@/lib/bookkeeping/engine'
import { isBookkeepingError } from '@/lib/bookkeeping/errors'
import { createServiceClient } from '@/lib/supabase/server'
import { buildInvoicePaymentWithCustomerCreditLines } from '@/lib/bookkeeping/customer-overpayment-lines'
import { planInvoiceCustomerPayment } from '@/lib/invoices/customer-payment-allocation'
import { eventBus } from '@/lib/events'
import { computePreviousAttributes } from '@/lib/webhooks/diff'
import { createLogger } from '@/lib/logger'
import { getCompanyEntityType } from '@/lib/company/entity-type'
import { equalOre, sumOre } from '@/lib/money'
import type { CreateJournalEntryInput, EntityType, Invoice } from '@/types'

const log = createLogger('invoices/mark-paid')

export interface MarkPaidCustomLine {
  account_number: string
  debit_amount: number
  credit_amount: number
  line_description?: string
}

export interface MarkPaidRequest {
  invoiceId: string
  /** ISO date; defaults to today. */
  paymentDate?: string
  /**
   * Explicit payment amount (invoice currency). Defaults to the custom-lines
   * debit total when lines are supplied, else the invoice's remaining amount.
   */
  paymentAmount?: number
  /** SEK adjustment for foreign-currency invoices. */
  exchangeRateDifference?: number
  customLines?: MarkPaidCustomLine[]
  notes?: string
  /** Bank transaction to link on the invoice_payments row, when applicable. */
  transactionId?: string | null
  /** Mandatory for every write surface; generated by trusted server routes. */
  idempotencyKey: string
  /** Correlation id returned to the caller and persisted in audit/outbox. */
  requestId: string
  paymentReference?: string | null
}

export interface MarkPaidWarning {
  code: string
  message: string
}

export type MarkPaidFailure = {
  ok: false
  code:
    | 'INVOICE_PAID_NOT_FOUND'
    | 'INVOICE_PAID_NOT_PAYABLE'
    | 'INVOICE_PAID_LINES_UNBALANCED'
    | 'INVOICE_PAID_NO_FISCAL_PERIOD'
    | 'INVOICE_PAID_BOOK_FAILED'
    | 'INVOICE_PAID_RACE'
    | 'VALIDATION_ERROR'
    | 'IDEMPOTENCY_KEY_REUSE'
    | 'PERIOD_LOCKED'
    | 'PAYMENT_CURRENCY_MISMATCH'
    | 'BANK_TRANSACTION_ALREADY_ALLOCATED'
    | 'COMPANY_WRITE_FORBIDDEN'
  details?: Record<string, unknown>
  /** Set when the engine threw a typed bookkeeping error (period lock etc.). */
  bookkeepingError?: unknown
}

export interface MarkPaidSuccess {
  ok: true
  invoice: Invoice
  journalEntryId: string | null
  paymentId: string | null
  appliedAmount: number
  overpaymentAmount: number
  newStatus: 'paid' | 'partially_paid'
  newPaidAmount: number
  newRemaining: number
  customerCreditId: string | null
  warnings: MarkPaidWarning[]
}

export type MarkPaidResult = MarkPaidSuccess | MarkPaidFailure

type LoadedInvoice = Invoice & {
  customer?: { id?: string; name?: string } | null
  items?: unknown[]
}

/**
 * Preflight: load + verify the invoice and plan the allocation. Shared by
 * the commit path and callers that need a dry-run preview.
 */
export async function prepareMarkInvoicePaid(
  supabase: SupabaseClient,
  companyId: string,
  request: MarkPaidRequest,
): Promise<
  | {
      ok: true
      invoice: LoadedInvoice
      paymentDate: string
      paymentAmount: number
      allocation: ReturnType<typeof planInvoiceCustomerPayment>
      accountingMethod: string
      entityType: EntityType
      useCashEntry: boolean
      isRealInvoice: boolean
    }
  | MarkPaidFailure
> {
  const { data: invoice, error: invoiceError } = await supabase
    .from('invoices')
    .select('*, customer:customers(*), items:invoice_items(*)')
    .eq('id', request.invoiceId)
    .eq('company_id', companyId)
    .maybeSingle()

  if (invoiceError || !invoice) {
    return { ok: false, code: 'INVOICE_PAID_NOT_FOUND' }
  }
  const typed = invoice as LoadedInvoice

  if (typed.document_type === 'delivery_note') {
    return {
      ok: false,
      code: 'VALIDATION_ERROR',
      details: { field: 'document_type', message: 'Följesedlar har ingen betalningslivscykel.' },
    }
  }
  if (typed.credited_invoice_id) {
    return {
      ok: false,
      code: 'VALIDATION_ERROR',
      details: {
        field: 'credited_invoice_id',
        message: 'Kreditfakturor kan inte markeras som betalda.',
      },
    }
  }
  if (typed.status !== 'sent' && typed.status !== 'overdue' && typed.status !== 'partially_paid') {
    return {
      ok: false,
      code: 'INVOICE_PAID_NOT_PAYABLE',
      details: { current_status: typed.status },
    }
  }

  if (request.customLines) {
    const totalDebit = sumOre(request.customLines.map((l) => l.debit_amount))
    const totalCredit = sumOre(request.customLines.map((l) => l.credit_amount))
    if (!equalOre(totalDebit, totalCredit) || totalDebit <= 0) {
      return {
        ok: false,
        code: 'INVOICE_PAID_LINES_UNBALANCED',
        details: { total_debit: totalDebit, total_credit: totalCredit },
      }
    }
  }

  const paymentDate = request.paymentDate || new Date().toISOString().split('T')[0]

  const { data: settings } = await supabase
    .from('company_settings')
    .select('accounting_method')
    .eq('company_id', companyId)
    .maybeSingle()
  const accountingMethod =
    (settings as { accounting_method?: string } | null)?.accounting_method ?? 'accrual'
  // Canonical legal form (B13) — companies.entity_type, no silent fallback.
  const entityType = await getCompanyEntityType(supabase, companyId)

  const invoiceAlreadyBooked = !!(typed as { journal_entry_id?: string | null }).journal_entry_id
  const useCashEntryCandidate = !invoiceAlreadyBooked && accountingMethod === 'cash'

  // Default path uses remaining_amount, not total — protects against
  // over-crediting AR when a concurrent partial payment slipped past the
  // pre-flight (the race-guard UPDATE later still protects the status flip).
  const paymentAmount =
    request.paymentAmount ??
    (request.customLines
      ? request.customLines.reduce((sum, line) => sum + line.debit_amount, 0)
      : (typed.remaining_amount ?? typed.total))

  const allocation = planInvoiceCustomerPayment(typed, paymentAmount)

  if (allocation.overpaymentAmount > 0 && request.customLines) {
    return {
      ok: false,
      code: 'VALIDATION_ERROR',
      details: {
        field: 'lines',
        message:
          'Överbetalningar med egna rader måste bokas som manuell verifikation; utelämna raderna så bokförs kundsaldot automatiskt.',
        overpayment_amount: allocation.overpaymentAmount,
      },
    }
  }
  if (allocation.overpaymentAmount > 0 && useCashEntryCandidate) {
    return {
      ok: false,
      code: 'VALIDATION_ERROR',
      details: {
        field: 'amount',
        message:
          'Överbetalning på kontantmetodsfaktura utan tidigare verifikation kräver manuella bokföringsrader.',
        overpayment_amount: allocation.overpaymentAmount,
      },
    }
  }

  if (useCashEntryCandidate && !allocation.isFullyPaid && !request.customLines) {
    return {
      ok: false,
      code: 'VALIDATION_ERROR',
      details: {
        field: 'amount',
        message: 'Kontantmetoden kräver full betalning eller explicita balanserade rader.',
      },
    }
  }

  const useCashEntry =
    useCashEntryCandidate && allocation.isFullyPaid && allocation.overpaymentAmount === 0
  const isRealInvoice = !typed.document_type || typed.document_type === 'invoice'

  return {
    ok: true,
    invoice: typed,
    paymentDate,
    paymentAmount,
    allocation,
    accountingMethod,
    entityType,
    useCashEntry,
    isRealInvoice,
  }
}

/**
 * Atomic settlement. The application only stages a balanced draft entry; the
 * service-role-only settle_customer_invoice RPC owns the economic transaction:
 * row/advisory locks, commit, payment allocation, invoice update, customer
 * credit, bank link, audit, outbox and idempotent result.
 */
export async function markInvoicePaid(
  supabase: SupabaseClient,
  companyId: string,
  userId: string,
  request: MarkPaidRequest,
): Promise<MarkPaidResult> {
  const payloadHash = createHash('sha256')
    .update(JSON.stringify({
      invoiceId: request.invoiceId,
      paymentDate: request.paymentDate ?? null,
      paymentAmount: request.paymentAmount ?? null,
      exchangeRateDifference: request.exchangeRateDifference ?? 0,
      customLines: request.customLines ?? null,
      notes: request.notes ?? null,
      transactionId: request.transactionId ?? null,
      paymentReference: request.paymentReference ?? null,
    }))
    .digest('hex')

  const service = createServiceClient()

  // Replay completed requests before reading mutable invoice state. A retry of
  // a successful full payment therefore returns the original result even though
  // the invoice is no longer in a payable status.
  const { data: replay, error: replayError } = await service.rpc(
    'get_financial_operation_result',
    {
      p_company_id: companyId,
      p_operation_type: 'customer_invoice_settlement',
      p_idempotency_key: request.idempotencyKey,
      p_payload_hash: payloadHash,
    },
  )
  if (replayError) {
    return mapAtomicSettlementError(replayError)
  }
  if (replay) {
    return hydrateAtomicCustomerResult(service, companyId, replay as AtomicCustomerSettlement)
  }

  const prepared = await prepareMarkInvoicePaid(supabase, companyId, request)
  if (!prepared.ok) return prepared

  const {
    invoice,
    paymentDate,
    paymentAmount,
    allocation,
    entityType,
    useCashEntry,
    isRealInvoice,
  } = prepared

  if (!isRealInvoice) {
    return {
      ok: false,
      code: 'VALIDATION_ERROR',
      details: { field: 'document_type', message: 'Endast kundfakturor kan slutregleras.' },
    }
  }

  let draftJournalEntryId: string | null = null
  try {
    if (request.customLines) {
      const fiscalPeriodId = await findFiscalPeriod(service, companyId, paymentDate)
      if (!fiscalPeriodId) {
        return { ok: false, code: 'INVOICE_PAID_NO_FISCAL_PERIOD', details: { payment_date: paymentDate } }
      }
      const input: CreateJournalEntryInput = {
        fiscal_period_id: fiscalPeriodId,
        entry_date: paymentDate,
        description: invoice.customer?.name
          ? `Inbetalning kundfaktura ${invoice.invoice_number}, ${invoice.customer.name}`
          : `Inbetalning kundfaktura ${invoice.invoice_number}`,
        source_type: useCashEntry ? 'invoice_cash_payment' : 'invoice_paid',
        source_id: invoice.id,
        lines: request.customLines.map((line) => ({
          account_number: line.account_number,
          debit_amount: line.debit_amount,
          credit_amount: line.credit_amount,
          line_description: line.line_description,
        })),
      }
      draftJournalEntryId = (await createDraftEntry(service, companyId, userId, input)).id
    } else if (allocation.overpaymentAmount > 0) {
      const fiscalPeriodId = await findFiscalPeriod(service, companyId, paymentDate)
      if (!fiscalPeriodId) {
        return { ok: false, code: 'INVOICE_PAID_NO_FISCAL_PERIOD', details: { payment_date: paymentDate } }
      }
      const description = invoice.customer?.name
        ? `Inbetalning kundfaktura ${invoice.invoice_number}, ${invoice.customer.name}`
        : `Inbetalning kundfaktura ${invoice.invoice_number}`
      draftJournalEntryId = (await createDraftEntry(service, companyId, userId, {
        fiscal_period_id: fiscalPeriodId,
        entry_date: paymentDate,
        description: `${description} med överbetalning`,
        source_type: 'invoice_paid',
        source_id: invoice.id,
        lines: buildInvoicePaymentWithCustomerCreditLines({
          bankAmount: paymentAmount,
          invoiceSettlementAmount: allocation.appliedAmount,
          customerCreditAmount: allocation.overpaymentAmount,
          description,
        }),
      })).id
    } else if (useCashEntry) {
      draftJournalEntryId = (await createInvoiceCashEntry(
        service,
        companyId,
        userId,
        invoice as Invoice,
        paymentDate,
        entityType,
        invoice.customer?.name,
        { draftOnly: true },
      ))?.id ?? null
    } else {
      draftJournalEntryId = (await createInvoicePaymentJournalEntry(
        service,
        companyId,
        userId,
        invoice as Invoice,
        paymentDate,
        request.exchangeRateDifference,
        invoice.customer?.name,
        allocation.appliedAmount,
        { draftOnly: true },
      ))?.id ?? null
    }
  } catch (error) {
    if (isBookkeepingError(error)) {
      log.warn('mark-paid: typed bookkeeping failure while staging draft', {
        invoiceId: invoice.id,
        companyId,
        requestId: request.requestId,
        reason: error instanceof Error ? error.message : 'unknown',
      })
      return {
        ok: false,
        code: 'INVOICE_PAID_BOOK_FAILED',
        bookkeepingError: error,
      }
    }
    log.error('mark-paid: draft journal entry creation failed', error as Error, {
      invoiceId: invoice.id,
      companyId,
      requestId: request.requestId,
    })
    return {
      ok: false,
      code: 'INVOICE_PAID_BOOK_FAILED',
    }
  }

  if (!draftJournalEntryId) {
    return {
      ok: false,
      code: 'INVOICE_PAID_NO_FISCAL_PERIOD',
      details: { payment_date: paymentDate },
    }
  }

  const { data, error } = await service.rpc('settle_customer_invoice', {
    p_company_id: companyId,
    p_invoice_id: invoice.id,
    p_actor_user_id: userId,
    p_payment_date: paymentDate,
    p_payment_amount: paymentAmount,
    p_currency: invoice.currency,
    p_exchange_rate_difference: request.exchangeRateDifference ?? 0,
    p_bank_transaction_id: request.transactionId ?? null,
    p_idempotency_key: request.idempotencyKey,
    p_payload_hash: payloadHash,
    p_request_id: request.requestId,
    p_payment_reference: request.paymentReference ?? null,
    p_notes: request.notes ?? null,
    p_draft_journal_entry_id: draftJournalEntryId,
    p_expected_remaining_amount: invoice.remaining_amount ?? invoice.total,
  })

  if (error || !data) {
    // A transport timeout can happen after PostgreSQL committed. Resolve that
    // ambiguity through the same idempotency record before touching the draft.
    const { data: committedReplay } = await service.rpc('get_financial_operation_result', {
      p_company_id: companyId,
      p_operation_type: 'customer_invoice_settlement',
      p_idempotency_key: request.idempotencyKey,
      p_payload_hash: payloadHash,
    })
    if (committedReplay) {
      return hydrateAtomicCustomerResult(
        service,
        companyId,
        committedReplay as AtomicCustomerSettlement,
      )
    }

    // Only a draft exists if the RPC rolled back. Cancelling a draft is a legal
    // state transition and has no ledger effect.
    const { error: cleanupError } = await service
      .from('journal_entries')
      .update({ status: 'cancelled' })
      .eq('id', draftJournalEntryId)
      .eq('company_id', companyId)
      .eq('status', 'draft')
    if (cleanupError) {
      log.error('mark-paid: failed to cancel rolled-back draft', cleanupError as Error, {
        invoiceId: invoice.id,
        draftJournalEntryId,
        requestId: request.requestId,
      })
    }
    const atomicError = error ?? new Error('Atomic settlement returned no result.')
    log.error('mark-paid: atomic settlement failed', atomicError as Error, {
      invoiceId: invoice.id,
      companyId,
      requestId: request.requestId,
    })
    return mapAtomicSettlementError(atomicError)
  }

  const result = await hydrateAtomicCustomerResult(
    service,
    companyId,
    data as AtomicCustomerSettlement,
  )

  if (result.ok) {
    // External fan-out is best effort because the durable outbox row was already
    // committed by PostgreSQL. A transient event-bus failure cannot corrupt the
    // economic operation and will be retried by the outbox worker.
    try {
      await eventBus.emit({
        type: 'invoice.paid',
        payload: {
          invoice: result.invoice,
          companyId,
          userId,
          paymentAmount: result.appliedAmount,
          paymentDate,
          previousAttributes: computePreviousAttributes(
            invoice as unknown as Record<string, unknown>,
            result.invoice as unknown as Record<string, unknown>,
          ),
        },
      })
    } catch (eventError) {
      log.warn('invoice.paid immediate dispatch failed; durable outbox retained', {
        invoiceId: invoice.id,
        requestId: request.requestId,
        reason: eventError instanceof Error ? eventError.message : 'unknown',
      })
    }
  }

  return result
}

type AtomicCustomerSettlement = {
  invoice_id: string
  payment_id: string | null
  journal_entry_id: string
  customer_credit_id: string | null
  applied_amount: number
  overpayment_amount: number
  paid_amount: number
  remaining_amount: number
  status: 'paid' | 'partially_paid'
  paid_at: string | null
  request_id: string
}

async function hydrateAtomicCustomerResult(
  service: SupabaseClient,
  companyId: string,
  atomic: AtomicCustomerSettlement,
): Promise<MarkPaidResult> {
  const { data: invoice, error } = await service
    .from('invoices')
    .select('*, customer:customers(*), items:invoice_items(*)')
    .eq('company_id', companyId)
    .eq('id', atomic.invoice_id)
    .single()

  if (error || !invoice) {
    log.error('mark-paid: atomic result could not be hydrated', error as Error, {
      companyId,
      invoiceId: atomic.invoice_id,
      requestId: atomic.request_id,
    })
    return { ok: false, code: 'INVOICE_PAID_BOOK_FAILED' }
  }

  return {
    ok: true,
    invoice: invoice as unknown as Invoice,
    journalEntryId: atomic.journal_entry_id,
    paymentId: atomic.payment_id,
    appliedAmount: Number(atomic.applied_amount),
    overpaymentAmount: Number(atomic.overpayment_amount),
    newStatus: atomic.status,
    newPaidAmount: Number(atomic.paid_amount),
    newRemaining: Number(atomic.remaining_amount),
    customerCreditId: atomic.customer_credit_id,
    warnings: [],
  }
}

function mapAtomicSettlementError(error: unknown): MarkPaidFailure {
  const candidate = error as { message?: string; details?: string; code?: string }
  let domainCode: string | null = null
  if (candidate.details) {
    try {
      const parsed = JSON.parse(candidate.details) as { code?: string }
      domainCode = parsed.code ?? null
    } catch {
      const match = candidate.details.match(/"code"\s*:\s*"([A-Z0-9_]+)"/)
      domainCode = match?.[1] ?? null
    }
  }

  const supported: MarkPaidFailure['code'][] = [
    'INVOICE_PAID_NOT_FOUND',
    'INVOICE_PAID_NOT_PAYABLE',
    'INVOICE_PAID_LINES_UNBALANCED',
    'INVOICE_PAID_NO_FISCAL_PERIOD',
    'INVOICE_PAID_BOOK_FAILED',
    'INVOICE_PAID_RACE',
    'VALIDATION_ERROR',
    'IDEMPOTENCY_KEY_REUSE',
    'PERIOD_LOCKED',
    'PAYMENT_CURRENCY_MISMATCH',
    'BANK_TRANSACTION_ALREADY_ALLOCATED',
    'COMPANY_WRITE_FORBIDDEN',
  ]
  const code = supported.includes(domainCode as MarkPaidFailure['code'])
    ? domainCode as MarkPaidFailure['code']
    : 'INVOICE_PAID_BOOK_FAILED'

  return {
    ok: false,
    code,
    details: { domain_code: domainCode ?? undefined },
  }
}
