#!/usr/bin/env npx tsx
/**
 * Generate a Supabase seed migration that loads data/assistant/faq-sv.json
 * (the 450-entry Swedish assistant FAQ) into assistant_faq_entries.
 *
 * Same rationale as scripts/generate-skill-bodies.ts:
 *   - Vercel builds have no DB, so the dataset must reach prod through the one
 *     trusted deploy path: supabase/migrations. The SQL is generated, never
 *     hand-authored.
 *   - Deterministic + append-only: a no-change run emits nothing (the dataset
 *     hash is tracked in scripts/.faq-seed-manifest.json); a dataset change
 *     emits ONE new timestamped migration that upserts every entry.
 *
 * Usage:
 *   npx tsx scripts/generate-faq-seed.ts          # emit a migration if the dataset changed
 *   npx tsx scripts/generate-faq-seed.ts --check  # CI guard: exit 1 if faq-sv.json changed
 *                                                  # without a regenerated seed migration
 */

import { createHash } from 'node:crypto'
import { writeFile, readFile } from 'node:fs/promises'
import { existsSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const ROOT = dirname(dirname(__filename))
const DATASET_PATH = join(ROOT, 'data', 'assistant', 'faq-sv.json')
const MIGRATIONS_DIR = join(ROOT, 'supabase', 'migrations')
const MANIFEST_PATH = join(ROOT, 'scripts', '.faq-seed-manifest.json')

const checkOnly = process.argv.includes('--check')

interface FaqEntry {
  id: string
  category: string
  intent: string
  user_questions: string[]
  short_answer_sv: string
  answer_sv: string
  sources: string[]
  required_permissions: string[]
  related_routes: string[]
  risk_level: 'low' | 'medium' | 'high'
  escalation: string | null
  updated_at: string
}

interface Manifest {
  hash: string
  entryCount: number
  migration: string
}

function sha256(s: string): string {
  return createHash('sha256').update(s, 'utf8').digest('hex')
}

/** Wrap a string in a dollar-quote tag guaranteed not to appear inside it. */
function dollarQuote(s: string): string {
  let tag = '$faq$'
  let n = 0
  while (s.includes(tag)) {
    tag = `$faq${n}$`
    n++
  }
  return `${tag}${s}${tag}`
}

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`
}

function sqlTextArray(items: string[]): string {
  if (items.length === 0) return `'{}'::text[]`
  return `array[${items.map(sqlStr).join(', ')}]::text[]`
}

function loadManifest(): Manifest | null {
  if (!existsSync(MANIFEST_PATH)) return null
  try {
    return JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) as Manifest
  } catch {
    return null
  }
}

function validate(entries: FaqEntry[]): void {
  // Product floor: the assistant ships with AT LEAST 450 curated entries.
  // New modules append — the dataset is allowed to grow past 450.
  if (entries.length < 450) {
    throw new Error(`Dataset must contain at least 450 entries, found ${entries.length}`)
  }
  const ids = new Set<string>()
  for (const e of entries) {
    if (ids.has(e.id)) throw new Error(`Duplicate id: ${e.id}`)
    ids.add(e.id)
    if (e.user_questions.length < 3 || e.user_questions.length > 6) {
      throw new Error(`${e.id}: user_questions must have 3-6 variants`)
    }
    if (!e.short_answer_sv.trim() || !e.answer_sv.trim()) {
      throw new Error(`${e.id}: empty answer`)
    }
    if (!['low', 'medium', 'high'].includes(e.risk_level)) {
      throw new Error(`${e.id}: invalid risk_level ${e.risk_level}`)
    }
  }
}

function buildMigrationSql(entries: FaqEntry[], datasetHash: string): string {
  const lines: string[] = []
  lines.push('-- AUTO-GENERATED by scripts/generate-faq-seed.ts — DO NOT EDIT BY HAND.')
  lines.push('-- Regenerate with `npm run faq:generate` after editing data/assistant/faq-sv.json.')
  lines.push('--')
  lines.push(`-- Dataset: data/assistant/faq-sv.json (${entries.length} entries, sha256:${datasetHash.slice(0, 16)}…)`)
  lines.push('-- Idempotent: upserts every entry by id and prunes rows no longer in the dataset,')
  lines.push('-- so the table always mirrors the committed JSON exactly.')
  lines.push('')
  lines.push('INSERT INTO public.assistant_faq_entries')
  lines.push('  (id, category, intent, user_questions, short_answer_sv, answer_sv, sources, required_permissions, related_routes, risk_level, escalation, updated_at, seeded_at)')
  lines.push('VALUES')

  const sorted = [...entries].sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))
  const rows = sorted.map((e) => {
    const parts = [
      sqlStr(e.id),
      sqlStr(e.category),
      sqlStr(e.intent),
      `${dollarQuote(JSON.stringify(e.user_questions))}::jsonb`,
      dollarQuote(e.short_answer_sv),
      dollarQuote(e.answer_sv),
      `${dollarQuote(JSON.stringify(e.sources))}::jsonb`,
      sqlTextArray(e.required_permissions),
      sqlTextArray(e.related_routes),
      sqlStr(e.risk_level),
      e.escalation === null ? 'NULL' : dollarQuote(e.escalation),
      `${sqlStr(e.updated_at)}::timestamptz`,
      'now()',
    ]
    return `  (${parts.join(', ')})`
  })
  lines.push(rows.join(',\n'))
  lines.push('ON CONFLICT (id) DO UPDATE SET')
  lines.push('  category = excluded.category,')
  lines.push('  intent = excluded.intent,')
  lines.push('  user_questions = excluded.user_questions,')
  lines.push('  short_answer_sv = excluded.short_answer_sv,')
  lines.push('  answer_sv = excluded.answer_sv,')
  lines.push('  sources = excluded.sources,')
  lines.push('  required_permissions = excluded.required_permissions,')
  lines.push('  related_routes = excluded.related_routes,')
  lines.push('  risk_level = excluded.risk_level,')
  lines.push('  escalation = excluded.escalation,')
  lines.push('  updated_at = excluded.updated_at,')
  lines.push('  seeded_at = now();')
  lines.push('')
  lines.push('-- Prune entries removed from the dataset so the table mirrors the JSON.')
  lines.push('DELETE FROM public.assistant_faq_entries')
  lines.push(`WHERE id NOT IN (${sorted.map((e) => sqlStr(e.id)).join(', ')});`)
  lines.push('')
  return lines.join('\n')
}

async function timestampName(): Promise<string> {
  const d = new Date()
  const pad = (n: number) => String(n).padStart(2, '0')
  const wallClock = `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`

  // Migrations run in filename order and some existing migrations carry
  // future-dated timestamps. A seed emitted with a lower timestamp would run
  // before the assistant_faq_entries DDL and fail — so always sort after the
  // newest existing migration.
  const { readdir } = await import('node:fs/promises')
  const existing = (await readdir(MIGRATIONS_DIR))
    .filter((f) => /^\d{14}_/.test(f))
    .map((f) => f.slice(0, 14))
    .sort()
  const latest = existing[existing.length - 1]
  if (latest && wallClock <= latest) {
    return String(BigInt(latest) + BigInt(1)).padStart(14, '0')
  }
  return wallClock
}

async function main(): Promise<void> {
  const raw = await readFile(DATASET_PATH, 'utf8')
  const entries = JSON.parse(raw) as FaqEntry[]
  validate(entries)

  const hash = sha256(raw)
  const manifest = loadManifest()

  if (manifest && manifest.hash === hash) {
    console.log('faq-seed: dataset unchanged — nothing to do.')
    return
  }

  if (checkOnly) {
    console.error(
      'faq-seed: data/assistant/faq-sv.json changed but no regenerated seed migration was committed.\n' +
        'Run `npm run faq:generate` and commit the new migration + manifest.',
    )
    process.exit(1)
  }

  const migrationName = `${await timestampName()}_seed_assistant_faq_entries.sql`
  const sql = buildMigrationSql(entries, hash)
  await writeFile(join(MIGRATIONS_DIR, migrationName), sql, 'utf8')
  await writeFile(
    MANIFEST_PATH,
    JSON.stringify({ hash, entryCount: entries.length, migration: migrationName }, null, 2) + '\n',
    'utf8',
  )
  console.log(`faq-seed: wrote supabase/migrations/${migrationName} (${entries.length} entries).`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
