-- =============================================================================
-- Supabase performance advisor: indexes
--
-- 1. duplicate_index (WARN): webhook_events had a unique index on (code) next
--    to its primary key on (code). Nothing references the extra index (no
--    constraint owns it); the primary key keeps uniqueness.
--
-- 2. unindexed_foreign_keys (INFO, 442): an index on every foreign key that
--    does not point at auth.users — 281 of them, 58 on company_id (which every
--    RLS policy filters on). Without one, each delete or key update on the
--    parent scans the child, and joins from the parent side cannot use an
--    index. The 161 audit/actor columns referencing auth.users (created_by,
--    approved_by, …) are deliberately left unindexed: auth.users rows are
--    almost never deleted and nothing queries by those columns.
--
-- unused_index (INFO) is not acted on: production has two companies, so
-- "never used" says nothing about what the indexes are for yet.
-- =============================================================================

DROP INDEX IF EXISTS public.webhook_events_code_uidx;

CREATE INDEX IF NOT EXISTS idx_accounting_manual_overrides_rule_decision_id_fk ON public.accounting_manual_overrides (rule_decision_id);  -- -> accounting_rule_decisions
CREATE INDEX IF NOT EXISTS idx_accounting_review_queue_rule_decision_id_fk ON public.accounting_review_queue (rule_decision_id);  -- -> accounting_rule_decisions
CREATE INDEX IF NOT EXISTS idx_accrual_schedule_installments_journal_entry_id_fk ON public.accrual_schedule_installments (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_accrual_schedules_invoice_item_id_fk ON public.accrual_schedules (invoice_item_id);  -- -> invoice_items
CREATE INDEX IF NOT EXISTS idx_accrual_schedules_origin_journal_entry_id_fk ON public.accrual_schedules (origin_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_accrual_schedules_supplier_invoice_item_id_fk ON public.accrual_schedules (supplier_invoice_item_id);  -- -> supplier_invoice_items
CREATE INDEX IF NOT EXISTS idx_agency_client_status_snapshots_company_id_fk ON public.agency_client_status_snapshots (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_agent_memory_superseded_by_fk ON public.agent_memory (superseded_by);  -- -> agent_memory
CREATE INDEX IF NOT EXISTS idx_agi_declarations_corrects_agi_id_fk ON public.agi_declarations (corrects_agi_id);  -- -> agi_declarations
CREATE INDEX IF NOT EXISTS idx_agi_declarations_salary_run_id_fk ON public.agi_declarations (salary_run_id);  -- -> salary_runs
CREATE INDEX IF NOT EXISTS idx_agi_declarations_tax_payment_journal_entry_id_fk ON public.agi_declarations (tax_payment_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_annual_report_audit_events_fiscal_period_id_fk ON public.annual_report_audit_events (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_annual_report_audit_events_project_id_fk ON public.annual_report_audit_events (project_id);  -- -> annual_report_projects
CREATE INDEX IF NOT EXISTS idx_annual_report_audit_events_report_version_id_fk ON public.annual_report_audit_events (report_version_id);  -- -> annual_report_versions
CREATE INDEX IF NOT EXISTS idx_annual_report_comparative_snapshots_source_fiscal__a778bf9a ON public.annual_report_comparative_snapshots (source_fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_annual_report_comparative_snapshots_source_version_id_fk ON public.annual_report_comparative_snapshots (source_version_id);  -- -> annual_report_versions
CREATE INDEX IF NOT EXISTS idx_annual_report_presentation_reclassifications_fisca_e8d4d9f4 ON public.annual_report_presentation_reclassifications (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_annual_report_presentation_reclassifications_project_id_fk ON public.annual_report_presentation_reclassifications (project_id);  -- -> annual_report_projects
CREATE INDEX IF NOT EXISTS idx_annual_report_projects_current_version_id_fk ON public.annual_report_projects (current_version_id);  -- -> annual_report_versions
CREATE INDEX IF NOT EXISTS idx_annual_report_projects_fiscal_period_id_fk ON public.annual_report_projects (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_annual_report_versions_fiscal_period_id_fk ON public.annual_report_versions (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_annual_report_versions_ixbrl_document_id_fk ON public.annual_report_versions (ixbrl_document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_annual_report_versions_pdf_document_id_fk ON public.annual_report_versions (pdf_document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_annual_report_versions_superseded_by_id_fk ON public.annual_report_versions (superseded_by_id);  -- -> annual_report_versions
CREATE INDEX IF NOT EXISTS idx_api_client_scopes_scope_code_fk ON public.api_client_scopes (scope_code);  -- -> api_scopes
CREATE INDEX IF NOT EXISTS idx_api_clients_agency_id_fk ON public.api_clients (agency_id);  -- -> agencies
CREATE INDEX IF NOT EXISTS idx_api_clients_company_id_fk ON public.api_clients (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_arsredovisning_narrative_confirmations_fiscal_period_id_fk ON public.arsredovisning_narrative_confirmations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_arsredovisning_narratives_fiscal_period_id_fk ON public.arsredovisning_narratives (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_arsredovisning_submissions_archived_document_id_fk ON public.arsredovisning_submissions (archived_document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_arsredovisning_submissions_dokument_id_fk ON public.arsredovisning_submissions (dokument_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_arsredovisning_submissions_fiscal_period_id_fk ON public.arsredovisning_submissions (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_auth_audit_events_company_id_fk ON public.auth_audit_events (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_automation_decisions_applied_journal_entry_id_fk ON public.automation_decisions (applied_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_automation_decisions_rule_id_fk ON public.automation_decisions (rule_id);  -- -> bookkeeping_automation_rules
CREATE INDEX IF NOT EXISTS idx_automation_decisions_transaction_id_fk ON public.automation_decisions (transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_bank_accounts_bank_connection_id_fk ON public.bank_accounts (bank_connection_id);  -- -> bank_connections
CREATE INDEX IF NOT EXISTS idx_bank_connections_bank_data_provider_id_fk ON public.bank_connections (bank_data_provider_id);  -- -> bank_data_providers
CREATE INDEX IF NOT EXISTS idx_bank_connections_company_id_fk ON public.bank_connections (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_bank_file_import_rows_transaction_id_fk ON public.bank_file_import_rows (transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_bankgiro_application_documents_application_id_fk ON public.bankgiro_application_documents (application_id);  -- -> bankgiro_applications
CREATE INDEX IF NOT EXISTS idx_bankgiro_application_documents_company_id_fk ON public.bankgiro_application_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_bankgiro_application_documents_document_id_fk ON public.bankgiro_application_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_bankgiro_applications_company_id_fk ON public.bankgiro_applications (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_bankgiro_applications_provider_id_fk ON public.bankgiro_applications (provider_id);  -- -> payment_providers
CREATE INDEX IF NOT EXISTS idx_bankgiro_provider_status_events_application_id_fk ON public.bankgiro_provider_status_events (application_id);  -- -> bankgiro_applications
CREATE INDEX IF NOT EXISTS idx_bankgiro_provider_status_events_company_id_fk ON public.bankgiro_provider_status_events (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_billing_checkout_sessions_fiscal_period_id_fk ON public.billing_checkout_sessions (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_billing_checkout_sessions_parent_subscription_id_fk ON public.billing_checkout_sessions (parent_subscription_id);  -- -> company_subscriptions
CREATE INDEX IF NOT EXISTS idx_billing_checkout_sessions_plan_version_id_fk ON public.billing_checkout_sessions (plan_version_id);  -- -> platform_plan_versions
CREATE INDEX IF NOT EXISTS idx_billing_events_company_id_fk ON public.billing_events (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_bookkeeping_automation_rules_agency_id_fk ON public.bookkeeping_automation_rules (agency_id);  -- -> agencies
CREATE INDEX IF NOT EXISTS idx_cash_accounts_bank_connection_id_fk ON public.cash_accounts (bank_connection_id);  -- -> bank_connections
CREATE INDEX IF NOT EXISTS idx_chat_messages_company_id_fk ON public.chat_messages (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_chat_sessions_company_id_fk ON public.chat_sessions (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_company_authorization_attestations_legal_text_version_id_fk ON public.company_authorization_attestations (legal_text_version_id);  -- -> legal_text_versions
CREATE INDEX IF NOT EXISTS idx_company_entitlements_feature_code_fk ON public.company_entitlements (feature_code);  -- -> platform_features
CREATE INDEX IF NOT EXISTS idx_company_subscription_change_requests_target_plan_v_3fa58865 ON public.company_subscription_change_requests (target_plan_version_id);  -- -> platform_plan_versions
CREATE INDEX IF NOT EXISTS idx_company_subscriptions_plan_id_fk ON public.company_subscriptions (plan_id);  -- -> platform_price_plans
CREATE INDEX IF NOT EXISTS idx_currency_revaluation_items_company_id_fk ON public.currency_revaluation_items (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_currency_revaluation_runs_entry_id_fk ON public.currency_revaluation_runs (entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_currency_revaluation_runs_fiscal_period_id_fk ON public.currency_revaluation_runs (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_currency_revaluation_runs_reversal_entry_id_fk ON public.currency_revaluation_runs (reversal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_customer_account_credits_customer_id_fk ON public.customer_account_credits (customer_id);  -- -> customers
CREATE INDEX IF NOT EXISTS idx_customer_account_credits_source_journal_entry_id_fk ON public.customer_account_credits (source_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_customer_account_credits_source_transaction_id_fk ON public.customer_account_credits (source_transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_deadlines_customer_id_fk ON public.deadlines (customer_id);  -- -> customers
CREATE INDEX IF NOT EXISTS idx_depreciation_schedules_journal_entry_id_fk ON public.depreciation_schedules (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_dividend_decisions_company_id_fk ON public.dividend_decisions (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_dividend_decisions_journal_entry_id_fk ON public.dividend_decisions (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_dividend_documents_company_id_fk ON public.dividend_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_dividend_documents_dividend_decision_id_fk ON public.dividend_documents (dividend_decision_id);  -- -> dividend_decisions
CREATE INDEX IF NOT EXISTS idx_dividend_documents_dividend_proposal_id_fk ON public.dividend_documents (dividend_proposal_id);  -- -> dividend_proposals
CREATE INDEX IF NOT EXISTS idx_dividend_documents_document_id_fk ON public.dividend_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_dividend_proposals_company_id_fk ON public.dividend_proposals (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_dividend_proposals_fiscal_period_id_fk ON public.dividend_proposals (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_document_attachments_superseded_by_id_fk ON public.document_attachments (superseded_by_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_event_log_company_id_fk ON public.event_log (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_financial_repair_runs_company_id_fk ON public.financial_repair_runs (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_fiscal_period_reopen_requests_closing_entry_id_fk ON public.fiscal_period_reopen_requests (closing_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_fiscal_period_reopen_requests_closing_reversal_entry_id_fk ON public.fiscal_period_reopen_requests (closing_reversal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_fiscal_period_reopen_requests_fiscal_period_id_fk ON public.fiscal_period_reopen_requests (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_fiscal_period_reopen_requests_opening_balance_entry_id_fk ON public.fiscal_period_reopen_requests (opening_balance_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_fiscal_period_reopen_requests_opening_balance_reve_d4baf95e ON public.fiscal_period_reopen_requests (opening_balance_reversal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_historical_bank_row_voucher_links_company_id_fk ON public.historical_bank_row_voucher_links (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_bank_row_voucher_links_journal_entry_id_fk ON public.historical_bank_row_voucher_links (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_historical_bank_statement_imports_fiscal_period_id_fk ON public.historical_bank_statement_imports (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_historical_bank_statement_rows_company_id_fk ON public.historical_bank_statement_rows (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_equity_reconciliation_documents_company_id_fk ON public.historical_equity_reconciliation_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_equity_reconciliation_documents_document_id_fk ON public.historical_equity_reconciliation_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_historical_equity_reconciliation_invalidations_com_da85a81f ON public.historical_equity_reconciliation_invalidations (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_equity_reconciliation_lines_company_id_fk ON public.historical_equity_reconciliation_lines (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_equity_reconciliation_lines_reconciliation_id_fk ON public.historical_equity_reconciliation_lines (reconciliation_id);  -- -> historical_equity_reconciliations
CREATE INDEX IF NOT EXISTS idx_historical_equity_reconciliations_fiscal_period_id_fk ON public.historical_equity_reconciliations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_historical_tax_reconciliation_documents_company_id_fk ON public.historical_tax_reconciliation_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_tax_reconciliation_documents_document_id_fk ON public.historical_tax_reconciliation_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_historical_tax_reconciliation_invalidations_company_id_fk ON public.historical_tax_reconciliation_invalidations (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_tax_reconciliations_fiscal_period_id_fk ON public.historical_tax_reconciliations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_historical_vat_reconciliation_documents_company_id_fk ON public.historical_vat_reconciliation_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_vat_reconciliation_documents_document_id_fk ON public.historical_vat_reconciliation_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_historical_vat_reconciliation_invalidations_company_id_fk ON public.historical_vat_reconciliation_invalidations (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_historical_vat_reconciliations_fiscal_period_id_fk ON public.historical_vat_reconciliations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_idempotency_keys_company_id_fk ON public.idempotency_keys (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_invoice_financing_applications_consent_id_fk ON public.invoice_financing_applications (consent_id);  -- -> signed_consents
CREATE INDEX IF NOT EXISTS idx_invoice_financing_applications_provider_slug_fk ON public.invoice_financing_applications (provider_slug);  -- -> invoice_financing_providers
CREATE INDEX IF NOT EXISTS idx_invoice_financing_events_company_id_fk ON public.invoice_financing_events (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_invoice_financing_settlements_journal_entry_id_fk ON public.invoice_financing_settlements (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_invoice_financing_settlements_transaction_id_fk ON public.invoice_financing_settlements (transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_invoice_inbox_items_duplicate_of_inbox_item_id_fk ON public.invoice_inbox_items (duplicate_of_inbox_item_id);  -- -> invoice_inbox_items
CREATE INDEX IF NOT EXISTS idx_invoice_inbox_items_duplicate_of_supplier_invoice_id_fk ON public.invoice_inbox_items (duplicate_of_supplier_invoice_id);  -- -> supplier_invoices
CREATE INDEX IF NOT EXISTS idx_invoice_inbox_items_matched_supplier_id_fk ON public.invoice_inbox_items (matched_supplier_id);  -- -> suppliers
CREATE INDEX IF NOT EXISTS idx_invoice_inbox_items_matched_transaction_id_fk ON public.invoice_inbox_items (matched_transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_invoice_payment_adjustments_invoice_id_fk ON public.invoice_payment_adjustments (invoice_id);  -- -> invoices
CREATE INDEX IF NOT EXISTS idx_invoice_payment_adjustments_journal_entry_id_fk ON public.invoice_payment_adjustments (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_invoice_payment_adjustments_transaction_id_fk ON public.invoice_payment_adjustments (transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_invoice_reminders_company_id_fk ON public.invoice_reminders (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_invoice_reminders_fee_journal_entry_id_fk ON public.invoice_reminders (fee_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_invoices_credited_invoice_id_fk ON public.invoices (credited_invoice_id);  -- -> invoices
CREATE INDEX IF NOT EXISTS idx_invoices_customer_id_fk ON public.invoices (customer_id);  -- -> customers
CREATE INDEX IF NOT EXISTS idx_invoices_payment_journal_entry_id_fk ON public.invoices (payment_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_journal_entry_lines_account_id_fk ON public.journal_entry_lines (account_id);  -- -> chart_of_accounts
CREATE INDEX IF NOT EXISTS idx_legal_acceptances_legal_text_version_id_fk ON public.legal_acceptances (legal_text_version_id);  -- -> legal_text_versions
CREATE INDEX IF NOT EXISTS idx_mapping_rules_company_id_fk ON public.mapping_rules (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_migrated_customer_receivables_customer_id_fk ON public.migrated_customer_receivables (customer_id);  -- -> customers
CREATE INDEX IF NOT EXISTS idx_migrated_customer_receivables_fiscal_period_id_fk ON public.migrated_customer_receivables (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_migrated_customer_receivables_sie_import_id_fk ON public.migrated_customer_receivables (sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_migrated_customer_receivables_superseded_by_fk ON public.migrated_customer_receivables (superseded_by);  -- -> migrated_customer_receivables
CREATE INDEX IF NOT EXISTS idx_migrated_receivable_documents_company_id_fk ON public.migrated_receivable_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_migrated_receivable_documents_document_id_fk ON public.migrated_receivable_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_migrated_receivable_payments_receivable_id_fk ON public.migrated_receivable_payments (receivable_id);  -- -> migrated_customer_receivables
CREATE INDEX IF NOT EXISTS idx_migrated_receivable_voucher_links_company_id_fk ON public.migrated_receivable_voucher_links (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_migrated_receivable_voucher_links_journal_entry_id_fk ON public.migrated_receivable_voucher_links (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payable_documents_company_id_fk ON public.migrated_supplier_payable_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payable_documents_document_id_fk ON public.migrated_supplier_payable_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payable_payments_payable_id_fk ON public.migrated_supplier_payable_payments (payable_id);  -- -> migrated_supplier_payables
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payable_voucher_links_company_id_fk ON public.migrated_supplier_payable_voucher_links (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payable_voucher_links_journal_entry_id_fk ON public.migrated_supplier_payable_voucher_links (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payables_fiscal_period_id_fk ON public.migrated_supplier_payables (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payables_sie_import_id_fk ON public.migrated_supplier_payables (sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payables_superseded_by_fk ON public.migrated_supplier_payables (superseded_by);  -- -> migrated_supplier_payables
CREATE INDEX IF NOT EXISTS idx_migrated_supplier_payables_supplier_id_fk ON public.migrated_supplier_payables (supplier_id);  -- -> suppliers
CREATE INDEX IF NOT EXISTS idx_notification_log_company_id_fk ON public.notification_log (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_onboarding_choices_company_id_fk ON public.onboarding_choices (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_onboarding_steps_company_id_fk ON public.onboarding_steps (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_one_time_purchases_fiscal_period_id_fk ON public.one_time_purchases (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_one_time_purchases_product_id_fk ON public.one_time_purchases (product_id);  -- -> platform_products
CREATE INDEX IF NOT EXISTS idx_payment_collection_events_payment_collection_id_fk ON public.payment_collection_events (payment_collection_id);  -- -> payment_collections
CREATE INDEX IF NOT EXISTS idx_payment_collections_company_id_fk ON public.payment_collections (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_payment_collections_invoice_id_fk ON public.payment_collections (invoice_id);  -- -> invoices
CREATE INDEX IF NOT EXISTS idx_payment_collections_mandate_id_fk ON public.payment_collections (mandate_id);  -- -> payment_mandates
CREATE INDEX IF NOT EXISTS idx_payment_collections_provider_id_fk ON public.payment_collections (provider_id);  -- -> payment_providers
CREATE INDEX IF NOT EXISTS idx_payment_mandates_company_id_fk ON public.payment_mandates (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_payment_mandates_customer_id_fk ON public.payment_mandates (customer_id);  -- -> customers
CREATE INDEX IF NOT EXISTS idx_payment_mandates_provider_id_fk ON public.payment_mandates (provider_id);  -- -> payment_providers
CREATE INDEX IF NOT EXISTS idx_payment_match_log_company_id_fk ON public.payment_match_log (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_payment_provider_accounts_bankgiro_application_id_fk ON public.payment_provider_accounts (bankgiro_application_id);  -- -> bankgiro_applications
CREATE INDEX IF NOT EXISTS idx_payment_provider_accounts_payment_provider_id_fk ON public.payment_provider_accounts (payment_provider_id);  -- -> payment_providers
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_items_collection_id_fk ON public.payment_reconciliation_items (collection_id);  -- -> payment_collections
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_items_company_id_fk ON public.payment_reconciliation_items (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_items_provider_id_fk ON public.payment_reconciliation_items (provider_id);  -- -> payment_providers
CREATE INDEX IF NOT EXISTS idx_payment_reconciliation_items_transaction_id_fk ON public.payment_reconciliation_items (transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_platform_plan_features_feature_id_fk ON public.platform_plan_features (feature_id);  -- -> platform_features
CREATE INDEX IF NOT EXISTS idx_platform_price_plans_product_id_fk ON public.platform_price_plans (product_id);  -- -> platform_products
CREATE INDEX IF NOT EXISTS idx_processing_history_causation_id_fk ON public.processing_history (causation_id);  -- -> processing_history
CREATE INDEX IF NOT EXISTS idx_processing_history_event_type_fk ON public.processing_history (event_type);  -- -> processing_event_types
CREATE INDEX IF NOT EXISTS idx_recurring_invoice_runs_invoice_id_fk ON public.recurring_invoice_runs (invoice_id);  -- -> invoices
CREATE INDEX IF NOT EXISTS idx_recurring_invoice_schedules_last_invoice_id_fk ON public.recurring_invoice_schedules (last_invoice_id);  -- -> invoices
CREATE INDEX IF NOT EXISTS idx_salary_payslip_deliveries_employee_id_fk ON public.salary_payslip_deliveries (employee_id);  -- -> employees
CREATE INDEX IF NOT EXISTS idx_salary_runs_avgifter_entry_id_fk ON public.salary_runs (avgifter_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_salary_runs_corrects_run_id_fk ON public.salary_runs (corrects_run_id);  -- -> salary_runs
CREATE INDEX IF NOT EXISTS idx_salary_runs_pension_entry_id_fk ON public.salary_runs (pension_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_salary_runs_salary_entry_id_fk ON public.salary_runs (salary_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_salary_runs_vacation_entry_id_fk ON public.salary_runs (vacation_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_sie_import_corrections_sie_import_id_fk ON public.sie_import_corrections (sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_sie_import_corrections_sie_import_session_id_fk ON public.sie_import_corrections (sie_import_session_id);  -- -> sie_parse_sessions
CREATE INDEX IF NOT EXISTS idx_sie_import_entry_reversals_sie_import_id_fk ON public.sie_import_entry_reversals (sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_sie_imports_fiscal_period_id_fk ON public.sie_imports (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_sie_imports_opening_balance_entry_id_fk ON public.sie_imports (opening_balance_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_sie_imports_replaces_import_id_fk ON public.sie_imports (replaces_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_sie_parse_sessions_replace_import_id_fk ON public.sie_parse_sessions (replace_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_sie_parse_sessions_sie_import_id_fk ON public.sie_parse_sessions (sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_signup_drafts_provisioned_agency_id_fk ON public.signup_drafts (provisioned_agency_id);  -- -> agencies
CREATE INDEX IF NOT EXISTS idx_signup_drafts_provisioned_company_id_fk ON public.signup_drafts (provisioned_company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_skattekonto_transactions_journal_entry_id_fk ON public.skattekonto_transactions (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_stripe_one_time_event_applications_company_id_fk ON public.stripe_one_time_event_applications (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_stripe_one_time_refunds_company_id_fk ON public.stripe_one_time_refunds (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_supplier_invoice_payments_journal_entry_id_fk ON public.supplier_invoice_payments (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_credited_invoice_id_fk ON public.supplier_invoices (credited_invoice_id);  -- -> supplier_invoices
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_payment_journal_entry_id_fk ON public.supplier_invoices (payment_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_registration_journal_entry_id_fk ON public.supplier_invoices (registration_journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_supplier_invoices_transaction_id_fk ON public.supplier_invoices (transaction_id);  -- -> transactions
CREATE INDEX IF NOT EXISTS idx_tax_declaration_adjustments_fiscal_period_id_fk ON public.tax_declaration_adjustments (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_tax_declaration_audit_events_fiscal_period_id_fk ON public.tax_declaration_audit_events (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_tax_declaration_audit_events_tax_declaration_project_id_fk ON public.tax_declaration_audit_events (tax_declaration_project_id);  -- -> tax_declaration_projects
CREATE INDEX IF NOT EXISTS idx_tax_declaration_exports_fiscal_period_id_fk ON public.tax_declaration_exports (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_tax_declaration_exports_tax_declaration_project_id_fk ON public.tax_declaration_exports (tax_declaration_project_id);  -- -> tax_declaration_projects
CREATE INDEX IF NOT EXISTS idx_tax_declaration_fields_fiscal_period_id_fk ON public.tax_declaration_fields (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_tax_declaration_questionnaire_answers_fiscal_period_id_fk ON public.tax_declaration_questionnaire_answers (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_tax_declaration_warnings_fiscal_period_id_fk ON public.tax_declaration_warnings (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_tax_declaration_warnings_tax_declaration_project_id_fk ON public.tax_declaration_warnings (tax_declaration_project_id);  -- -> tax_declaration_projects
CREATE INDEX IF NOT EXISTS idx_tax_submission_events_tax_submission_id_fk ON public.tax_submission_events (tax_submission_id);  -- -> tax_submissions
CREATE INDEX IF NOT EXISTS idx_transaction_match_candidates_company_id_fk ON public.transaction_match_candidates (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_transactions_automation_decision_id_fk ON public.transactions (automation_decision_id);  -- -> automation_decisions
CREATE INDEX IF NOT EXISTS idx_transactions_bank_account_id_fk ON public.transactions (bank_account_id);  -- -> bank_accounts
CREATE INDEX IF NOT EXISTS idx_transactions_bank_connection_id_fk ON public.transactions (bank_connection_id);  -- -> bank_connections
CREATE INDEX IF NOT EXISTS idx_transactions_cash_account_id_fk ON public.transactions (cash_account_id);  -- -> cash_accounts
CREATE INDEX IF NOT EXISTS idx_transactions_invoice_id_fk ON public.transactions (invoice_id);  -- -> invoices
CREATE INDEX IF NOT EXISTS idx_transactions_potential_invoice_id_fk ON public.transactions (potential_invoice_id);  -- -> invoices
CREATE INDEX IF NOT EXISTS idx_user_preferences_active_company_id_fk ON public.user_preferences (active_company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_voucher_gap_explanations_fiscal_period_id_fk ON public.voucher_gap_explanations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_voucher_sequences_fiscal_period_id_fk ON public.voucher_sequences (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_company_id_fk ON public.webhook_endpoints (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_webhooks_created_by_api_key_id_fk ON public.webhooks (created_by_api_key_id);  -- -> api_keys
CREATE INDEX IF NOT EXISTS idx_year_end_adjustments_company_id_fk ON public.year_end_adjustments (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_adjustments_journal_entry_id_fk ON public.year_end_adjustments (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_adjustments_project_id_fk ON public.year_end_adjustments (project_id);  -- -> year_end_projects
CREATE INDEX IF NOT EXISTS idx_year_end_annotation_documents_company_id_fk ON public.year_end_annotation_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_annotation_documents_document_id_fk ON public.year_end_annotation_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_year_end_annotations_company_id_fk ON public.year_end_annotations (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_annotations_fiscal_period_id_fk ON public.year_end_annotations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_annotations_supersedes_id_fk ON public.year_end_annotations (supersedes_id);  -- -> year_end_annotations
CREATE INDEX IF NOT EXISTS idx_year_end_checks_company_id_fk ON public.year_end_checks (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_company_snapshots_fiscal_period_id_fk ON public.year_end_company_snapshots (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_company_snapshots_source_sie_import_id_fk ON public.year_end_company_snapshots (source_sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_year_end_deliverables_company_id_fk ON public.year_end_deliverables (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_deliverables_document_id_fk ON public.year_end_deliverables (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_year_end_deliverables_project_id_fk ON public.year_end_deliverables (project_id);  -- -> year_end_projects
CREATE INDEX IF NOT EXISTS idx_year_end_equity_events_fiscal_period_id_fk ON public.year_end_equity_events (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_equity_events_journal_entry_id_fk ON public.year_end_equity_events (journal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_equity_events_source_sie_import_id_fk ON public.year_end_equity_events (source_sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_year_end_external_ap_reconciliation_documents_company_id_fk ON public.year_end_external_ap_reconciliation_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_external_ap_reconciliation_documents_docu_6a82d124 ON public.year_end_external_ap_reconciliation_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_year_end_external_ap_reconciliation_invalidations__0f1e75e7 ON public.year_end_external_ap_reconciliation_invalidations (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_external_ap_reconciliations_fiscal_period_id_fk ON public.year_end_external_ap_reconciliations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_external_ap_reconciliations_source_sie_im_e502e3fe ON public.year_end_external_ap_reconciliations (source_sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_year_end_external_ar_reconciliation_documents_company_id_fk ON public.year_end_external_ar_reconciliation_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_external_ar_reconciliation_documents_docu_ded73443 ON public.year_end_external_ar_reconciliation_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_year_end_external_ar_reconciliation_invalidations__c93f391a ON public.year_end_external_ar_reconciliation_invalidations (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_external_ar_reconciliations_fiscal_period_id_fk ON public.year_end_external_ar_reconciliations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_external_ar_reconciliations_source_sie_im_9fd42c3c ON public.year_end_external_ar_reconciliations (source_sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_year_end_external_bank_reconciliation_documents_do_063a5f03 ON public.year_end_external_bank_reconciliation_documents (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_year_end_external_bank_reconciliation_documents_co_81d841f6 ON public.year_end_external_bank_reconciliation_documents (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_external_bank_reconciliation_invalidation_294ae111 ON public.year_end_external_bank_reconciliation_invalidations (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_external_bank_reconciliations_fiscal_period_id_fk ON public.year_end_external_bank_reconciliations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_fx_rate_snapshots_fiscal_period_id_fk ON public.year_end_fx_rate_snapshots (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_historical_workpaper_events_company_id_fk ON public.year_end_historical_workpaper_events (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_historical_workpaper_events_document_id_fk ON public.year_end_historical_workpaper_events (document_id);  -- -> document_attachments
CREATE INDEX IF NOT EXISTS idx_year_end_historical_workpaper_events_fiscal_period_id_fk ON public.year_end_historical_workpaper_events (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_historical_workpaper_events_source_sie_im_4130c911 ON public.year_end_historical_workpaper_events (source_sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_year_end_historical_workpapers_fiscal_period_id_fk ON public.year_end_historical_workpapers (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_historical_workpapers_pending_sie_import_id_fk ON public.year_end_historical_workpapers (pending_sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_year_end_manual_cash_reconciliation_invalidations__1bb039ab ON public.year_end_manual_cash_reconciliation_invalidations (invalidated_by_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_manual_cash_reconciliation_invalidations__c20db5e5 ON public.year_end_manual_cash_reconciliation_invalidations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_manual_cash_reconciliations_cash_account_id_fk ON public.year_end_manual_cash_reconciliations (cash_account_id);  -- -> cash_accounts
CREATE INDEX IF NOT EXISTS idx_year_end_manual_cash_reconciliations_fiscal_period_id_fk ON public.year_end_manual_cash_reconciliations (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_outbox_company_id_fk ON public.year_end_outbox (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_outbox_fiscal_period_id_fk ON public.year_end_outbox (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_previews_fiscal_period_id_fk ON public.year_end_previews (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_profit_dispositions_fiscal_period_id_fk ON public.year_end_profit_dispositions (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_projects_fiscal_period_id_fk ON public.year_end_projects (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_projects_sie_import_id_fk ON public.year_end_projects (sie_import_id);  -- -> sie_imports
CREATE INDEX IF NOT EXISTS idx_year_end_projects_year_end_run_id_fk ON public.year_end_projects (year_end_run_id);  -- -> year_end_runs
CREATE INDEX IF NOT EXISTS idx_year_end_purchase_access_one_time_purchase_id_fk ON public.year_end_purchase_access (one_time_purchase_id);  -- -> one_time_purchases
CREATE INDEX IF NOT EXISTS idx_year_end_purchase_access_year_end_project_id_fk ON public.year_end_purchase_access (year_end_project_id);  -- -> year_end_projects
CREATE INDEX IF NOT EXISTS idx_year_end_run_acknowledgements_company_id_fk ON public.year_end_run_acknowledgements (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_run_acknowledgements_fiscal_period_id_fk ON public.year_end_run_acknowledgements (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_runs_closing_entry_id_fk ON public.year_end_runs (closing_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_runs_fiscal_period_id_fk ON public.year_end_runs (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_runs_next_period_id_fk ON public.year_end_runs (next_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_runs_opening_balance_entry_id_fk ON public.year_end_runs (opening_balance_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_runs_preview_id_fk ON public.year_end_runs (preview_id);  -- -> year_end_previews
CREATE INDEX IF NOT EXISTS idx_year_end_runs_reopen_request_id_fk ON public.year_end_runs (reopen_request_id);  -- -> fiscal_period_reopen_requests
CREATE INDEX IF NOT EXISTS idx_year_end_runs_reopening_reversal_entry_id_fk ON public.year_end_runs (reopening_reversal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_runs_revaluation_entry_id_fk ON public.year_end_runs (revaluation_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_runs_revaluation_reversal_entry_id_fk ON public.year_end_runs (revaluation_reversal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_scheduled_reversals_company_id_fk ON public.year_end_scheduled_reversals (company_id);  -- -> companies
CREATE INDEX IF NOT EXISTS idx_year_end_scheduled_reversals_fiscal_period_id_fk ON public.year_end_scheduled_reversals (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_scheduled_reversals_reversal_entry_id_fk ON public.year_end_scheduled_reversals (reversal_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_scheduled_reversals_source_entry_id_fk ON public.year_end_scheduled_reversals (source_entry_id);  -- -> journal_entries
CREATE INDEX IF NOT EXISTS idx_year_end_staged_adjustments_fiscal_period_id_fk ON public.year_end_staged_adjustments (fiscal_period_id);  -- -> fiscal_periods
CREATE INDEX IF NOT EXISTS idx_year_end_staged_adjustments_posted_entry_id_fk ON public.year_end_staged_adjustments (posted_entry_id);  -- -> journal_entries
