-- Assistant FAQ knowledge base (Batch 10).
--
-- Stores the seeded Swedish FAQ (exactly 450 entries, data/assistant/faq-sv.json)
-- that the in-app assistant searches BEFORE falling back to skills/atoms.
-- Entries are global product/accounting knowledge — not company data — so the
-- table is readable by every authenticated user and writable only via
-- migrations/service role (the seed migration is generated by
-- scripts/generate-faq-seed.ts, npm run faq:generate).
--
-- Retrieval: a generated tsvector column (swedish config) over question
-- variants + intent + answers, GIN-indexed, exposed through the
-- search_assistant_faq() RPC. In-process keyword scoring in
-- lib/agent/faq/retriever.ts complements this for deterministic ranking and
-- offline/test use. pgvector embedding search can be layered on later without
-- schema changes to this table (add an embedding column + index).

-- Immutable helper so the generated search_text column can flatten the
-- user_questions jsonb string array (generated columns reject subqueries).
-- Safe to mark immutable: output depends only on the input value.
create or replace function public.assistant_faq_questions_text(p_questions jsonb)
returns text
language sql
immutable
parallel safe
as $$
  select coalesce(string_agg(value, ' '), '')
  from jsonb_array_elements_text(p_questions)
$$;

create table if not exists public.assistant_faq_entries (
  id text primary key,
  category text not null,
  intent text not null,
  user_questions jsonb not null,
  short_answer_sv text not null,
  answer_sv text not null,
  sources jsonb not null default '[]'::jsonb,
  required_permissions text[] not null default '{}',
  related_routes text[] not null default '{}',
  risk_level text not null check (risk_level in ('low', 'medium', 'high')),
  escalation text,
  updated_at timestamptz not null,
  seeded_at timestamptz not null default now(),
  -- Full-text search over everything a user's question could hit.
  search_text text generated always as (
    lower(
      public.assistant_faq_questions_text(user_questions)
      || ' ' || replace(intent, '_', ' ')
      || ' ' || category
      || ' ' || short_answer_sv
      || ' ' || answer_sv
    )
  ) stored,
  constraint assistant_faq_entries_questions_shape check (
    jsonb_typeof(user_questions) = 'array'
    and jsonb_array_length(user_questions) between 3 and 6
  ),
  constraint assistant_faq_entries_nonempty check (
    length(trim(short_answer_sv)) > 0 and length(trim(answer_sv)) > 0
  )
);

comment on table public.assistant_faq_entries is
  'Seeded Swedish assistant FAQ (450 entries). Global knowledge — read-only for users; written only by generated seed migrations.';

-- tsvector index for the RPC search path (swedish stemming).
create index if not exists assistant_faq_entries_search_idx
  on public.assistant_faq_entries
  using gin (to_tsvector('swedish', search_text));

create index if not exists assistant_faq_entries_category_idx
  on public.assistant_faq_entries (category);

-- ── RLS ─────────────────────────────────────────────────────────────────────
alter table public.assistant_faq_entries enable row level security;

-- Global knowledge base: every authenticated user may read. No user-facing
-- write policies — inserts/updates flow through generated seed migrations
-- (postgres role) or the service role, both of which bypass RLS.
drop policy if exists "assistant_faq_read_authenticated" on public.assistant_faq_entries;
create policy "assistant_faq_read_authenticated"
  on public.assistant_faq_entries for select
  to authenticated
  using (true);

-- ── Search RPC ──────────────────────────────────────────────────────────────
-- websearch_to_tsquery tolerates free-form user questions ("hur bokför jag
-- lön?") without syntax errors; ts_rank_cd gives cover-density ranking so
-- entries where the query terms appear close together (question variants)
-- rank above incidental body matches. SECURITY INVOKER + RLS keeps this
-- readable by any authenticated caller and nobody else.
create or replace function public.search_assistant_faq(
  p_query text,
  p_limit integer default 5
)
returns table (
  id text,
  category text,
  intent text,
  user_questions jsonb,
  short_answer_sv text,
  answer_sv text,
  sources jsonb,
  required_permissions text[],
  related_routes text[],
  risk_level text,
  escalation text,
  rank real
)
language sql
stable
security invoker
set search_path = public
as $$
  select
    e.id,
    e.category,
    e.intent,
    e.user_questions,
    e.short_answer_sv,
    e.answer_sv,
    e.sources,
    e.required_permissions,
    e.related_routes,
    e.risk_level,
    e.escalation,
    ts_rank_cd(
      to_tsvector('swedish', e.search_text),
      websearch_to_tsquery('swedish', p_query)
    ) as rank
  from public.assistant_faq_entries e
  where to_tsvector('swedish', e.search_text)
        @@ websearch_to_tsquery('swedish', p_query)
  order by rank desc, e.id
  limit greatest(1, least(coalesce(p_limit, 5), 20));
$$;

grant execute on function public.search_assistant_faq(text, integer) to authenticated;

-- Status helper for the assistant settings UI: entry count + last seed time
-- without shipping 450 rows to the client.
create or replace function public.assistant_faq_status()
returns table (entry_count bigint, last_seeded_at timestamptz, last_updated_at timestamptz)
language sql
stable
security invoker
set search_path = public
as $$
  select
    count(*)::bigint as entry_count,
    max(seeded_at) as last_seeded_at,
    max(updated_at) as last_updated_at
  from public.assistant_faq_entries;
$$;

grant execute on function public.assistant_faq_status() to authenticated;
